nanomsg/nng

.travis.yml

For now we have problems with TCP tests racing against each
other and this can lead to failures due to port use.  In the
old nanomsg repo we assigned several different port numbers on
the command line, but we lack that here generally.  However, we
feel that parallel testing is of little merit; its better to
build dedicated stress tests if that is what is desired.
We also use the matrix stuff a bit more sensibly, only installing
packages we actually use. This will likely lead to shorter startup
times.
Finally we cleaned up the environment so that we have sane defaults
for most environment variables.

Updates to Travis CI configuration, serialize testing (TCP).

---

src/core/transport.c
src/core/transport.h
tests/trantest.h

We automatically register inproc, TCP, and IPC.  We can add more now
by just calling nni_tran_register().  (There is no unregister support.)
This requires transports to have access to the AIO framework (so that needs
to be something we consider), and a few nni_sock calls to get socket options.
Going forward we should version the ops vectors, and move to pushing down
transport options from the framework via setopt calls -- there is no reason
really that transports need to know all these.

fixes #37 Make transports pluggable

---

perf/perf.c
src/core/device.c
src/core/protocol.c
src/core/protocol.h
src/core/socket.c
src/core/socket.h
src/nng.c
src/nng.h
src/nng_compat.c
src/protocol/bus/bus.c
src/protocol/pair/pair.c
src/protocol/pipeline/pull.c
src/protocol/pipeline/push.c
src/protocol/pubsub/pub.c
src/protocol/pubsub/sub.c
src/protocol/reqrep/rep.c
src/protocol/reqrep/req.c
src/protocol/survey/respond.c
src/protocol/survey/survey.c
tests/bus.c
tests/event.c
tests/pipeline.c
tests/pollfd.c
tests/pubsub.c
tests/reqrep.c
tests/scalability.c
tests/sock.c
tests/survey.c
tests/tcp.c
tests/trantest.h

fixes #38 Make protocols "pluggable", or at least optional
This is a breaking change, as we've done away with the central
registered list of protocols, and instead demand the user call
nng_xxx_open() where xxx is a protocol name.  (We did keep a
table around in the compat framework though.)
There is a nice way for protocols to plug in via
an nni_proto_open(), where they can use a generic constructor
that they use to build a protocol specific constructor (passing
their ops vector in.)

fixes #44 open protocol by "name" (symbol) instead number

---

src/core/socket.c
tests/CMakeLists.txt
tests/convey.c
tests/convey.h
tests/inproc.c
tests/ipc.c
tests/tcp.c
tests/trantest.h

This arranges for port numbers (and also btw IPC paths) to be dynamically incremented both during multi-test executable runs, and across executables.  It should eliminate all the TCP listen failures.

fixes #48 tcp sometimes fails to get a port

---

perf/perf.c
src/core/aio.c
src/core/aio.h
src/core/platform.h
src/core/taskq.c
src/core/thread.c
src/core/thread.h
src/core/timer.c
src/platform/posix/posix_thread.c
src/platform/windows/win_thread.c

A little benchmarking showed that we were encountering far too many
wakeups, leading to severe performance degradation; we had a bunch
of threads all sleeping on the same condition variable (taskqs)
and this woke them all up, resulting in heavy mutex contention.
Since we only need one of the threads to wake, and we don't care which
one, let's just wake only one.  This reduced RTT latency from about
240 us down to about 30 s.  (1/8 of the former cost.)
There's still a bunch of tuning to do; performance remains worse than
we would like.

Thundering herd kills performance.

---

src/core/message.c
src/core/message.h
src/core/socket.c
src/nng.c
src/nng.h
src/nng_compat.c
src/protocol/bus/bus.c
src/protocol/pair/pair_v1.c
src/protocol/reqrep/rep.c
src/protocol/reqrep/req.c
src/protocol/survey/respond.c
src/protocol/survey/survey.c
src/transport/inproc/inproc.c
tests/CMakeLists.txt
tests/message.c
tests/survey.c

This makes the operations that work on headers start with
nni_msg_header or nng_msg_header.  It also renames _trunc to
_chop (same strlen as _trim), and renames prepend to insert.
We add a shorthand for clearing message content, and make
better use of the endian safe 32-bit accessors too.

Unify the msg API.

---

src/core/options.c
tests/pollfd.c
tests/sock.c

We never set the fd->sn_init member, causing new fds to be allocated
on each request for a new pollfd, and causing old ones to leak, and
worse may be even to not get notified.  While here, we arrange for
a bit richer testing against the various options.

Leaking poll fds.

---

src/core/endpt.c
src/core/endpt.h
src/core/options.c
src/core/options.h
src/core/pipe.c
src/core/socket.c
src/core/socket.h
src/core/transport.c
src/core/transport.h
src/nng.c
src/nng.h
src/transport/ipc/ipc.c
src/transport/tcp/tcp.c
tests/sock.c

This supports creating listeners and dialers, managing options
on them (though only a few options are supported at present),
starting them and closing them, all independently.

Endpoint API completely implemented.

---

src/core/init.c
src/core/options.c
src/core/options.h
src/core/protocol.c
src/core/protocol.h
src/nng.c
src/nng.h
src/protocol/pair/pair_v1.c
src/transport/inproc/inproc.c
src/transport/ipc/ipc.c
src/transport/tcp/tcp.c
tests/inproc.c
tests/pair1.c

This permits option numbers to be allocated based on string name.
Eventually all the option values will be replaced with option
names.  This will facilitate transports (ZeroTier) that may need
further options.

Implement dynamic option numbering.

---

CMakeLists.txt
src/CMakeLists.txt
src/core/platform.h
src/nng.c
src/nng.h
src/platform/posix/posix_udp.c
src/transport/zerotier/zerotier.adoc
src/transport/zerotier/zerotier.c
tests/CMakeLists.txt
tests/sock.c
tests/trantest.h
tests/zt.c

The ZeroTier transport is experimental at this point, and not enabled
by default.  It does not work with Windows yet (the Windows platform
needs UDP support first.)
Configure with -DNNG_ENABLE_ZEROTIER=yes -DNNG_ZEROTIER_SOUCE=<path>
The <path> must point to a dev branch of the ZeroTierOne source tree,
checked out, and built with a libzerotiercore.a in the top directory,
and a ZeroTierOne.h header located at include.  The build will add
-lc++ to the compile, as the ZeroTier core functionality is written in
C++ and needs some runtime support (e.g. new, delete, etc.)

ZeroTier transport implementation (work funded by Capitar IT Group BV)

---

src/protocol/pipeline/pull.c
src/protocol/pubsub/sub.c
src/protocol/survey/respond.c
src/protocol/survey/survey.c

We looked at other options, but this is the least intrusive, even though
it means that the protocols have to set it up.  The reason is that transports
have different methods of receiving messages, and there is no framework code
between the transport and the protocol.

fixes #85 Protocols need to set msg pipe

---

src/CMakeLists.txt
src/core/options.c
src/platform/windows/win_impl.h
src/platform/windows/win_sockaddr.c
src/platform/windows/win_tcp.c
src/platform/windows/win_thread.c
src/platform/windows/win_udp.c
tests/CMakeLists.txt
tests/trantest.h
tests/udp.c

This implements the basic UDP functionality for Windows (required
for ZeroTier for example).  We have also introduced a UDP test suite
to validate that this actually works.  While here a few Windows
compilation warnings / nits were fixed.

Windows UDP support.

---

src/core/device.c
src/core/socket.c
src/nng.c

This eliminates the separate threads used for devices, letting them
benefit from the new aio framework.  It also eliminates the legacy
nni_sock_sendmsg and nni_sock_recvmsg internal APIs.
It would appear that there is an opportunity here to provide asynchronous
device support out to userland as well, exposing an aio to them.  That
work is deferred to later.

fixes #46 make device() use aios directly

---

.appveyor.yml
.travis.yml
README.adoc

This updates to use Circle CI by default, but we leave Travis in place
(but only one default build and one coverage build) until we can move it.
We also switch to using ninja for performance reasons.
The hope is to get to using CircleCI for everything except Windows.  The
AppVeyor build needs cleanups and should switch to ninja later.

CI updates.

---

src/core/aio.c
src/transport/ipc/ipc.c
src/transport/tcp/tcp.c
src/transport/tls/tls.c
src/transport/ws/websocket.c

I'm pretty sure I need to go back and review the handling of
send messages for websocket too.  We still have a receive leak
in websocket and leaks caused by the new URL parsing code which
needs to be refactored.

Fix leaks on send.

---

docs/nng_ws.adoc
src/nng.h
src/platform/posix/posix_thread.c
src/supplemental/http/http.c
src/supplemental/http/http.h
src/supplemental/tls/mbedtls/tls.c
src/supplemental/tls/tls.h
src/supplemental/websocket/websocket.c
src/supplemental/websocket/websocket.h
src/transport/tls/tls.c
src/transport/tls/tls.h
src/transport/ws/websocket.c
src/transport/ws/websocket.h
tests/wss.c
tests/wssfile.c

It is useful to have support for validating that a peer *was*
verified, especially in the presence of optional validation.
We have added a property that does this, NNG_OPT_TLS_VERIFIED.
Further, all the old NNG_OPT_WSS_TLS_* property names have also been
renamed to generic NNG_OPT_TLS property names, which have been
moved to nng.h to facilitate reuse and sharing, with the comments
moved and corrected as well.
Finally, the man pages have been updated, with substantial
improvements to the nng_ws man page in particular.

fixes #206 Want NNG_OPT_TLS_VERIFIED option

---

src/core/file.c
src/core/file.h
src/platform/posix/posix_impl.h
src/platform/windows/win_impl.h
src/supplemental/http/http.h
src/supplemental/http/server.c
src/supplemental/websocket/websocket.c
tests/httpserver.c

These changes are a key enabling step required to present a clean and
usable API for user applications.  This doesn't make the API public
yet, and we still need to do some work around supporting full directory
trees and sanitizing URLs (to scrub out "/.." and such), but it gets
us much much closer.

Refactor HTTP server API.

---

src/core/aio.c
src/core/aio.h
src/core/endpt.c
src/core/url.c
src/nng.c
src/platform/posix/posix_epdesc.c
src/platform/windows/win_ipc.c
src/platform/windows/win_tcp.c
src/supplemental/http/http_client.c
src/supplemental/http/http_public.c
src/supplemental/http/http_server.c
src/supplemental/websocket/websocket.c
src/transport/inproc/inproc.c
src/transport/ipc/ipc.c
src/transport/tcp/tcp.c
src/transport/tls/tls.c
src/transport/ws/websocket.c
src/transport/zerotier/zerotier.c
tests/httpserver.c
tests/resolv.c

This addresses the use of the pipe special field, and eliminates it.
The message APIs (recvmsg, sendmsg) need to be updated as well still,
but I want to handle that as part of a separate issue.

fixes #171 Refactor aio to use generic data fields

---

src/platform/posix/posix_epdesc.c
src/platform/posix/posix_pipedesc.c
src/platform/posix/posix_pollq.h
src/platform/posix/posix_pollq_poll.c
src/platform/posix/posix_udp.c

This change is being made to facilitate the work done for the
kqueue port.  We have created two new functions, nni_posix_pollq_init
and nni_posix_pollq_fini, which can be used when creating or destroying
the pollq nodes.  Then nodes are *added* and *removed* from the pollq
structure with nni_posix_pollq_add and nni_posix_pollq_remove.  The
add function in particular MUST NEVER be called unless the node has
a valid file descriptor.

Simply posix pollq architecture somewhat.

---

perf/perf.c
src/CMakeLists.txt
src/core/platform.h
src/nng.c
src/nng.h
src/supplemental/util/CMakeLists.txt
src/supplemental/util/platform.c
src/supplemental/util/platform.h
tests/device.c
tests/multistress.c
tests/pipeline.c
tests/platform.c
tests/pollfd.c
tests/pubsub.c
tests/reconnect.c
tests/scalability.c
tests/sock.c
tests/synch.c
tests/trantest.h

This introduces portable primitives for time, random numbers,
synchronization primitives, and threading.  These are somewhat
primitive (least common denominiators), but they can help with writing
portable applications, especially our own demo apps.

Introduce 'porting layer' Public API.

---

src/platform/posix/posix_epdesc.c
src/platform/posix/posix_pipedesc.c
src/platform/posix/posix_pollq_poll.c

It was possible for pollq arm to be called on a node that was removed
in some circumstances -- particularly and ep that was closed in the
callback.
While here, lets use normal booleans for closed state, and only call
the arm function (which is not free -- typicall it involves a mutex
and may even involve a system call) if we are going to arm some events.
We also initialize these things properly, and clean up a stale comment.
This work is done to faciliate the kqueue work by @liamstask.

Fixes for POSIX pollq structure.

---

CMakeLists.txt
src/CMakeLists.txt
src/platform/posix/posix_config.h
src/platform/posix/posix_pollq_kqueue.c
src/transport/ipc/ipc.c

Initial cut at kqueue support for #35
This passes all tests on my machine, will see how it does on CI. Happy to rename/reorg as needed.
A couple thoughts:
* since some of the poller API (add, remove, enable, disable) may involve syscalls, it would nice to return errors from those routines and handle them accordingly, possibly in a future PR
* i wasn't totally clear on the expected handling of event flags - it looks like the existing poll implementation treats event flag manipulation as a cheap operation (it just manipulates userspace memory in the poll implementation), but since epoll and kqueue implementations might prefer to use the provided syscall interfaces to enable/disable events as distinct from adding/removing nodes, it could be nice to take that into consideration and minimize …

kqueue: add kqueue-based pollq implementation

---

CMakeLists.txt
src/core/defs.h
src/core/endpt.c
src/core/platform.h
src/platform/posix/posix_aio.h
src/platform/posix/posix_epdesc.c
src/platform/posix/posix_tcp.c
src/platform/windows/win_tcp.c
src/supplemental/http/http_server.c
src/transport/tcp/tcp.c
src/transport/tls/tls.c
src/transport/zerotier/zerotier.c
tests/tcp.c
tests/tls.c
tests/zt.c
tools/nngcat/nngcat.c

This causes TCP, TLS, and ZT endpoints to resolve any
wildcards, and even IP addresses, when reporting the listen
URL.  The dialer URL is reported unresolved.  Test cases
for this are added as well, and nngcat actually reports this
if --verbose is supplied.

fixes #262 NNG_OPT_URL should be resolved

---

.circleci/config.yml
.travis.yml

the [failed ci run](https://travis-ci.org/nanomsg/nng/jobs/349661097) for https://github.com/nanomsg/nng/pull/264 doesn't have many actionable details about what failed.
by setting the `CTEST_OUTPUT_ON_FAILURE` environment variable, the ctest runner will at least dump details about which assertions failed in the event of a failure, which should help with diagnosis.

ci: dump failure details on test failure

---

.circleci/build-and-test.sh
.circleci/config.yml
.circleci/images/clang/Dockerfile
.circleci/images/docker-deploy.sh
.circleci/images/gcc/Dockerfile

fixes #202
Includes build configs for clang and gcc on linux. It's possible to setup macOS as well, but requires an explicit support request to CircleCI for open source projects.
These run in parallel and are passing build & test for both, and uploading coverage info on the gcc image. I believe this represents parity with the travis build config, such that it could be dropped.
**Caveats**
Currently, the builds must install dependencies each time, which can be pretty slow. The recommended way to avoid this is to use custom docker images that include the dependencies - docker images are cached by circle ci.
This involves a little more coordination, since those docker images would be hosted on docker hub (hub.docker.com) and should probably be managed under a nanomsg organization (there's …

circle ci: add workflows for linux clang and gcc builds

---

docs/man/libnng.adoc
docs/man/nng_sleep_aio.adoc
src/core/aio.c
src/core/aio.h
src/nng.c
src/nng.h
tests/aio.c

This adds nng_sleep_aio(), and tests it, and documents it.
We want this to make writing certain async services easier.
We can probably use this to eliminate some of the timeouts and separate timeout thread too!

fixes #281 desire nng_sleep_aio()

---

docs/man/nng_sleep_aio.adoc
src/core/aio.c
tests/aio.c

The first problem was that using nng_sleep_aio
was found to reset the timeout, and this caused subsequent
operations to start failing with timeouts when reusing
the AIO for other operations.
The second thing is that we think it would be nicer if the
presence of real aio timeouts were still honored, so that
if the timeout is shorter than the sleep time, then we get
back an NNG_ETIMEDOUT like every other operation, and we
get back a 0 if the logical sleep operation completes
normally.

nng_sleep_aio should honor aio timeout.

---

CMakeLists.txt
src/CMakeLists.txt
src/platform/posix/posix_pollq_epoll.c

fixes #33
This is ultimately pretty similar to the kqueue PR, main differences are:
* the epoll oneshot flag behavior allows us to avoid an explicit call to disable events as in kqueue, as they are disabled as soon as they are reported via `epoll_wait()`
* using the pipe fds to wake the poll thread in destroy appears to be necessary, as just closing the `epfd` doesn't work
Other than that, I think most of the integration effort for the kqueue PR made this one substantially more straightforward :)

epoll: add epoll-based pollq implementation

---

tests/zt.c

ZT test fails because of missing homedir.

Need to create zt home for dialer

---

src/core/aio.c
src/core/aio.h
src/supplemental/websocket/websocket.c
src/transport/ipc/ipc.c
src/transport/tcp/tcp.c
src/transport/tls/tls.c
src/transport/zerotier/zerotier.c

fixes #325 synchronous aio completion crash
fixes #327 move nni_clock() operations to outside the nni_aio_lk.
This work was done for the context tree, and is necessary to properly
enable that branch.

fixes #324 nni_aio_set_synch leads to race condition

---

docs/man/nng_options.5.adoc
src/compat/nanomsg/nn.c
src/core/msgqueue.c
src/core/msgqueue.h
src/core/socket.c
src/nng.h
src/transport/tcp/tcp.c
src/transport/tls/tls.c
tests/sock.c

Ultimately, this just removes the support for lingering altogether.
Based on prior experience, lingering has always been unreliable, and
was removed in legacy libnanomsg ages ago.
The problem is that operating system support for lingering is very
inconsistent at best, and for some transports the very concept is somewhat
meaningless.
Making things worse, we were never able to adequately capture an exit()
event from another thread -- so lingering was always a false promise.
Applications that need to be sure that messages are delivered should
either include an ack in their protocol, use req/rep (which has an ack),
or inject a suitable delay of their own.
For things going over local networks, an extra delay of 100 msec should
be sufficient *most of the time*.
fixes #<issue number> <issue …

fixes #308 Close can block

---

src/platform/posix/posix_resolv_gai.c

this will fix these two tests failing on my fedora 27 box
[toppk@static build]$  ../build/tests/tcp
Failures:
* Assertion Failed (Malformed TCP addresses do not panic)
File: ../tests/tcp.c
Line: 54
Test: nng_listen(s1, "tcp://127.0.0.1.32", ((void *)0), 0) == NNG_EADDRINVAL
FAIL    ../build/tests/tcp                                     1.093s
[toppk@static build]$  ../build/tests/tls
Failures:
* Assertion Failed (Malformed TLS addresses do not panic)
File: ../tests/tls.c
Line: 259
Test: nng_listen(s1, "tls+tcp://127.0.0.1.32", ((void *)0), 0) == NNG_EADDRINVAL
FAIL    ../build/tests/tls                                     2.531s
[toppk@static build]$

fixes bad address tests in tcp and tls

---

src/core/aio.c
src/core/taskq.c
src/core/taskq.h

This changes the array of flags, which was confusing, brittle, and
racy, into a much simpler reference (busy) count on the task structures.
This allows us to support certain kinds of "reentrant" dispatching,
where either a synchronous or asynchronous task can reschedule / dispatch
itself.  The new code also helps reduce certain lock pressure, as a bonus.

fixes #445 crash in taskq_thread

---

docs/man/nng_pipe_notify.3.adoc
src/core/pipe.c
src/core/socket.c
src/core/socket.h
src/nng.c
src/nng.h
src/protocol/bus0/bus.c
src/protocol/pair0/pair.c
src/protocol/pair1/pair.c
src/protocol/pipeline0/pull.c
src/protocol/pubsub0/sub.c
src/protocol/reqrep0/rep.c
src/protocol/reqrep0/xrep.c
src/protocol/survey0/respond.c
src/protocol/survey0/survey.c
src/protocol/survey0/xrespond.c
src/protocol/survey0/xsurvey.c
tests/pipe.c

This changes the signature of nng_pipe_notify(), and the associated
events.  The documentation is updated to reflect this.
We have also broken the lock up so that we don't hold the master
socket lock for some of these things, which may have beneficial
impact on performance.

fixes #449 Want more flexible pipe events

---

src/platform/posix/posix_aio.h

On Alpine Linux, this was noticed.  Obviously sys/types.h needs to be present for almost any non-trivial program on Linux or POSIX systems.

fixes #462 mode_t missing during compilation

---

src/compat/nanomsg/nn.c
src/core/url.c
src/supplemental/http/http_server.c
src/supplemental/websocket/websocket.c
src/supplemental/websocket/websocket.h
src/transport/ws/websocket.c
tests/CMakeLists.txt
tests/compat_ws.c

fixes #464 Support NN_WS_MSG_TYPE option (compat)
fixes #415 websocket does not honor recv maxsize
This fixes a significant (and security) issue in websocket, where the
code does not honor a maximum receive size.  We've exposed new API
(internal) to set the limit on the frame size, and we've changed the
default to *unlimited* for that internal API.  (But the default for SP
sockets, which are the only consumers at present, is still 1MB just like
all other SP transports.)

fixes #474 websocket listen on ws://*:<x> fails

---

CMakeLists.txt
docs/BUILD_ANDROID.adoc
docs/BUILD_CROSSCOMPILE.adoc
docs/BUILD_IOS.adoc
src/platform/posix/posix_file.c
src/platform/posix/posix_pollq_epoll.c

This enables the software to be built for Android, going back to
at least Android SDK r15 (IceCreamSandwich) and at least up to
SDK r27 (Oreo).  Older versions of Android may work, but we have
no way to build them to test.
While here we have changed our CMake configuration to disable
building tools or tests when we detect a cross-compile situation.
Documentation for cross-compilation is updated as well.

fixes #477 Android NDK build configuration

---

docs/man/nng_ipc.7.adoc
src/core/url.c
src/transport/ipc/ipc.c

This special cases the URL parser for inproc and IPC urls,
changing so that they no longer parse the thing after the ://
as anything special.  This allows IPC URLs to be relative.

fixes #509 We need "relative" IPC URLs

---

src/core/aio.c

This changes nni_aio_begin so that it immediately terminates when
it encounters aio->a_closed, much like it does for aio->a_stop.
The semantic for nni_aio_close() is supposed to be like nni_aio_stop(),
but without blocking.
I suspect that this might be responsible for use-after-free bugs that
seem to have been rearing their head lately.

fixes #533 nni_aio_begin should not dispatch task on NNG_ECLOSED.

---

docs/man/libnng.3.adoc
docs/man/nng_http_server_res_error.3http.adoc
docs/man/nng_http_server_set_error_file.3http.adoc
docs/man/nng_http_server_set_error_page.3http.adoc
src/supplemental/http/http.h
src/supplemental/http/http_api.h
src/supplemental/http/http_msg.c
src/supplemental/http/http_public.c
src/supplemental/http/http_server.c
tests/httpserver.c

This adds some new API calls to allow applications to add custom static content for defined error codes.

fixes #539 Feature request: customizable http error page

---

src/core/url.c

A missing return in nni_url_parse causes the special handling of ipc and inproc to be overwritten and the URL to be parsed completely. 
This results in the memory allocated by the strdup to leak.
It also means ipc and inproc URLs are canonicalized, not a bad thing per se, but this contradicts the documentation and breaks compatibility with nanomsg legacy code.

nni_url_parse does not handle ipc and inproc specially

---

src/core/dialer.c
src/core/listener.c
src/core/socket.c
src/core/socket.h
tests/pipe.c
tests/sock.c

fixes #565 Option getting should validate sizes more aggressively
fixes #563 Reconnect timeouts should be settable on dialers
fixes #562 pipe test is fragile
This fixes a number of things, but the regression is most important.
Note that long term we should look at some kind of different single lock for adding pipes or endpoints to sockets, under a single global lock for the socket.

fixes #564 Race regression caused by#522

---

CMakeLists.txt
src/platform/posix/posix_resolv_gai.c
src/platform/windows/win_resolv.c

Adding support for QNX.
- Updated cmake to support QNX
- Resolved issue on QNX where calls to getaddrinfo() would fail due to hints,ai_socktype not being explicitly set. I also explicitly set hints.ai_socktype on the windows platform. This was not necessary, however I think there is value in keeping the code consistent on both platforms.

Added QNX support

---

src/platform/posix/posix_alloc.c
src/platform/posix/posix_file.c
src/platform/windows/win_file.c
src/platform/windows/win_thread.c
src/protocol/pubsub0/sub.c

Windows actually allocates an object of size zero when calling
malloc on size zero.  This is unusual behavior, and we just
add logic to work more like malloc on POSIX systems.

fixes #611 Memory Leaks under Windows

---

tests/multistress.c
tests/reqstress.c

This converts the tests to use async I/O callbacks instead of
threads for running tests.  This should greatly reduce the
amount of pressure we apply to the system.  On macOS the
time to start up with a pressure of 500 is significantly less
than under the old system.  Plus, as we are no longer at the mercy
of the scheduler, we're far more likely to get a successful test.

fixes #620 Stress tests are too stressful in CI/CD

---

src/platform/posix/posix_pollq_epoll.c

The POLLHUP (or rather EPOLLHUP) flag does not quite mean the same
thing in Linux, and we've seen random failures where we will sometimes
get this event on a socket that is freshly connected.  This might be
a bug in Linux, but it is easy enough to workaround -- we just don't
watch for it at all.

fixes #653 Weird connect failures in dialer (multistress)

---

docs/man/CMakeLists.txt
docs/man/libnng.3.adoc
docs/man/nng_aio_begin.3.adoc
docs/man/nng_aio_defer.3.adoc
docs/man/nng_aio_finish.3.adoc
docs/man/nng_http_handler_alloc.3http.adoc
src/nng.c
src/nng.h
tests/aio.c

This also creates the nng_aio_begin and nng_aio_defer APIs, and documents and tests them.

fixes #506 AIO "providers" need a way to call nni_aio_schedule.

---

_includes/tip_version.html

All the man page docs that are not the latest released version give a notice, saying that the current docs being viewed are not the latest, and offer a link to the latest.  This fixes the broken link; formerly it was pointing to nng.html, now it points to index.html.

Make docs for old versions and tip point to the correct page

---

docs/man/nng_opts_parse.3supp.adoc
src/supplemental/util/options.c
src/supplemental/util/options.h

fixes #715 nng_opts_parse() uses const incorrectly

---

src/nng.c

Both the man page and the comment (in nng.h) of nng_send()
say that the buffer is freed only if the function succeeds.
The previous code always freed (if the flag was set). This
change only frees if we succeed.

Only free in nng_send() if we succeed.

---

docs/man/nng_dial.3.adoc
docs/man/nng_listen.3.adoc

Fixes #731 `nng_dial` and `nng_listen` return `NNG_EINVAL` on invalid URL

Update docs for `nng_dial` and `nng_listen`

---

src/CMakeLists.txt

This is a one-liner: the include directory associated with the exported library target was not exported, meaning that when importing the library target it was necessary to manually add the corresponding include directory. With this fix, it is possible to import the nng target properly without having to deal with the include directory manually.
I should also point out that in order to work outside of the main build system, one has to add "find_package(Threads REQUIRED)" in order to define the Threads::Threads target. The minimum cmake version should also be set at 3.1 or higher, otherwise one has to tweak cmake policies a little bit.

fix cmake target include directory exporting

---

docs/man/libnng.3.adoc
docs/man/nng_http_handler_alloc.3http.adoc
docs/man/nng_http_handler_collect_body.3http.adoc
src/supplemental/http/http.h
src/supplemental/http/http_api.h
src/supplemental/http/http_msg.c
src/supplemental/http/http_public.c
src/supplemental/http/http_server.c
tests/httpserver.c

This adds a new API, nng_http_handler_collect_body(), and test cases and documentation for same.
This is necessary to simplify post handling for REST API services, for example.

fixes #738 http server needs a way to collect request entity data

---

docs/man/nng_http_handler_alloc.3http.adoc
src/supplemental/http/http.h
src/supplemental/http/http_api.h
src/supplemental/http/http_msg.c
src/supplemental/http/http_public.c
src/supplemental/http/http_server.c
tests/httpserver.c

This also cleans up error pages a bit, and makes freeing REQ and RES objects safe even if they are NULL.

fixes #745 HTTP server redirect handler

---

src/platform/windows/win_file.c

Hi~
I find that the windows version `nni_plat_file_type` don't get correct result with root directory like "D:"、"D:\"、"D:/" etc. Replace `FindFirstFile` with `GetFileAttributes` yields correct result.
p.s. My computer runs on a Windows7x64 system.

Fix win file type

---

CMakeLists.txt
src/platform/posix/posix_thread.c

This enables a CMake option which will use the rlimit value for the stack size -- but only on Windows.  This is off by default, but apps needing this can configure it to get larger stacks.

fixes #767 Want tunable stack size

---

docs/man/nng_http_conn_transact.3http.adoc
docs/man/nng_http_handler_collect_body.3http.adoc
src/supplemental/http/CMakeLists.txt
src/supplemental/http/http_api.h
src/supplemental/http/http_chunk.c
src/supplemental/http/http_client.c
src/supplemental/http/http_conn.c
tests/httpclient.c

This is the client side only, although the work is structured to
support server applications.  The chunked API is for now private,
although the intent to is to make it public for applications who
really want to use it.
Note that chunked transfer encoding puts data through extra copies.
First it copies through the buffering area (because I have to be able
to extract variable length strings from inside the data stream), and then
again to reassemble the chunks into a single unified object.
We do assume that the user wants the entire thing as a single object.
This means that using this to pull unbounded data will just silently
consume all memory. Use caution!
Note that the above format should …

fixes #682 Support for Chunked Transfer Coding

---

src/CMakeLists.txt

This change allows to use nng as part of a bigger project using add_subdirectory.
e.g.: somebody adds nng as external dependency using:
```
FetchContent_Declare(
nng
URL https://github.com/nanomsg/nng/archive/v1.1.0.zip
)
FetchContent_GetProperties(nng)
if (NOT nng_POPULATED)
FetchContent_Populate(nng)
add_subdirectory(${nng_SOURCE_DIR} ${nng_BINARY_DIR})
endif()
```
and then later uses nng as target link library:
`target_link_library(nng_example nng)`
it will find the headers of (e.g. nng.h) using this change

Allow nng to be consumed in "add_subdirectory" scenarios

---

src/CMakeLists.txt

I'm working on updating my Python bindings to use the new source code layout (splitting out `include`), and found out that nng no longer builds correctly on the Docker image I use to build packages on CI.  I [made an issue in pynng](https://github.com/codypiersall/pynng/issues/15) and I have tracked down the breaking change to https://github.com/nanomsg/nng/commit/77984b14a65c0a7387c97f3d36f947dd17358744.
To be honest I'm not really sure what's going on.  For some reason, in the Docker image, the test programs aren't getting linked with `librt` for `clock_gettime()`, but I'm not seeing the issue on my actual Linux box.
As far as I can tell, this change fixes the issues, but I really don't know why.  I don't know much about CMake.  There's probably a better fix :-).

The toplevel sets threads already, not needed here.

---

CMakeLists.txt
src/core/taskq.c
src/platform/posix/posix_resolv_gai.c
src/platform/windows/win_resolv.c

Although there are a number of recommendations in #769 on how to reduce the memory footprint, I am submitting a PR that deals mostly with just the title: provide a mechanism for limiting the number of worker threads. This PR exposes CMake variables to set the number of resolver and taskq threads, respectively. Maybe a separate Issue is warranted, for tracking change to default stack sizes of various internal threads?
I tested this using the async demo on a Ubuntu VM running on Windows. By default, 25 threads are created on my machine for the async demo, and with these changes I was able to reduce the number of resolver threads to 1 and the number of taskq threads to 2:
```
$ cmake -G Ninja -DNNG_RESOLV_CONCURRENCY=1 -DNNG_NUM_TASKQ_THREADS=2 ..
```
With these changes, I was able to run …

fixes #769 How to limit worker threads

---

include/nng/supplemental/tcp/tcp.h
src/core/platform.h
src/platform/posix/posix_tcp.h
src/platform/posix/posix_tcpconn.c
src/platform/posix/posix_tcpdial.c
src/platform/posix/posix_tcplisten.c
src/platform/windows/win_impl.h
src/platform/windows/win_tcp.h
src/platform/windows/win_tcpconn.c
src/platform/windows/win_tcpdial.c
src/platform/windows/win_tcplisten.c
src/supplemental/http/http_api.h
src/supplemental/http/http_conn.c
src/supplemental/tcp/tcp.c
src/supplemental/tls/mbedtls/tls.c
src/supplemental/tls/none/tls.c
src/supplemental/tls/tls_api.h
src/supplemental/websocket/websocket.c
src/supplemental/websocket/websocket.h
src/transport/tcp/tcp.c
src/transport/tls/tls.c
src/transport/ws/websocket.c
tests/tcp.c
tests/tcpsupp.c

This changes much of the internal API for TCP option handling, and
includes hooks for some of this in various consumers.  Note that the
consumers still need to have additional work done to complete them,
which will be part of providing public "raw" TLS and WebSocket APIs.
We would also like to finish addressing the call sites of
nni_tcp_listener_start() that assume the sockaddr is modified --
it would be superior to use the NNG_OPT_LOCADDR option.  Thaat will be
addressed in a follow up PR.

fixes #825 TCP public API should use generic setopt/getopt

---

docs/man/nng_close.3.adoc
docs/man/nng_ctx_close.3.adoc
docs/man/nng_dial.3.adoc
docs/man/nng_pipe_close.3.adoc
docs/man/nng_pipe_getopt.3.adoc
docs/man/nng_recv.3.adoc
docs/man/nng_strfree.3.adoc

fixes #867 doc references to non-existant NNG_OPT_LINGER
Probably doesn't need additional warning/text, just remove references to NNG_OPT_LINGER and fix some other minor typos I've come across.

fixes #867 doc references to non-existant NNG_OPT_LINGER

---

docs/man/nng_sub_open.3.adoc

fixes #875 man page for nng_sub_open should use nng_sub0_open_raw for raw mode in DESCRIPTION section
In nng_sub_open document in the DESCRIPTION section 'nng_sub0_open_raw' should  be used for 'raw' socket.

Corrected function name

---

src/platform/windows/win_thread.c

fixes #868 Build failed on MinGW (mingw-w64) nng 1.1.1
Define an InterlockedAddNoFence64() function using gcc's atomics on
mingw(32|64)
(https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html)

Fix bug #868

---

docs/man/nng_pipe_notify.3.adoc
include/nng/nng.h
src/nng.c

fixes #894 nng_pipe_notify could use nng_pipe_ev typedef instead of int
`nng_pipe_notify()` uses `nng_pipe_ev` enum typedef instead of `int`

fixes #894 nng_pipe_notify could use nng_pipe_ev typedef instead of int

---

include/nng/nng.h
src/core/stream.c

fixes #903 Stream get_string implementation missing
This will probably conflict with #901.  In case the get/set naming is intentional and desired, making this independent of that.
If #901 is accepted, just make the one line change from here and delete this PR.  =)

fixes #903 Stream get_string implementation missing

---

src/core/message.c
tests/message.c

This was mentioned as a possible cause of #862, but doesn't actually fix it.
A couple dozen of messages can be exchanged without issue, but eventually one gets delivered through the wrong pipe.

nng_msg_dup correctly duplicates pipe (mentioned in #862)

---

docs/man/nng_inproc.7.adoc
src/core/msgqueue.c
src/core/msgqueue.h
src/core/protocol.h
src/core/socket.c
src/transport/inproc/inproc.c
tests/set_recvmaxsize.c

This also eliminates the enforcement of NNG_OPT_RECVMAXSZ for inproc,
which never really made much sense.  This helps inproc go faster.
While here, also clean up the entry point for protocols to support
a drain option, since we don't use that anywhere.

fixes #815 Eliminate socket filters on message queues

---

CMakeLists.txt

The main CMakeLists.txt file defines NNG_USE_ARC4_RANDOM for Mac OS but posix_rand.c checks NNG_USE_ARC4RANDOM. This pull request changes fixes the mismatch.

Fix ARC4RANDOM define mismatch

---

src/core/idhash.c

fixes #931 `nng_ctx_send` can block forever
This implements the first solution I suggested in the issue (having the `for` loop exit after probing all slots). I have not had a chance to test this in the system that I originally found the bug in but I will do so tomorrow.

fixes #931 nng_ctx_send can block forever

---

src/core/options.h

The functions nng_dialer_setopt_uint64 and nng_dialer_setopt_uint64 are
declared in nng.h but not defined, causing errors at runtime of programs
that expect them to be defined.

Add uint64 to generated legacy nng_setopt_* functions.

---

src/protocol/pubsub0/pub.c
src/protocol/pubsub0/sub.c

fixes #923,  fixes #935 RECVBUF/SENDBUF has variable type
Based on my previous experiences with pull requests here (and my understanding of SemVer), the documentation has the final say on things. In this case, the documentation says that the the options are of type `int` even though, logically, they are `size_t`.
I did nothing to account for the potential differences between the types but I really just copied the `nng_socket` implementation and that has apparently been good enough.

fixes #923 #935 RECVBUF/SENDBUF has variable type

---

src/core/platform.h
src/core/stats.c
src/platform/posix/posix_atomic.c
src/platform/windows/win_thread.c
src/supplemental/tls/mbedtls/tls.c
src/supplemental/tls/tls_common.c

This also introduces a more efficient reference counting usage based
on atomics, rather than locks.

fix #946 Use after free in TLS

---

demo/async/client.c
demo/async/server.c
demo/raw/raw.c

It is not used but prevents demos from being compiled on Windows.

Remove redundant <sys/time.h> include.

---

docs/man/nng_options.5.adoc
src/core/socket.c

This removes the default 1MB limit on maximum receive sizes.
Applications intended for deployment in insecure or hostile
environments should choose a sensible default for NNG_OPT_RECVMAXSZ.

fixes #954 large message fails with no error message

---

src/supplemental/websocket/websocket.c

Under high load, the websocket server can wind up completing the message callback instead of the stream one, leading to leaked messages, and possibly data corruption.

fixes #976 websocket stream calls incorrect completion callback

---

include/nng/protocol/reqrep0/rep.h

Maybe it doesn't make a difference in the end, but I think it's more correct this way.

fixes condition for the nng_rep_open_raw macro

---

docs/man/nng_stream_recv.3str.adoc
include/nng/nng.h
src/platform/posix/posix_ipcconn.c
src/platform/posix/posix_tcpconn.c
src/platform/windows/win_ipcconn.c
src/platform/windows/win_tcpconn.c

This seems to pass the test suite, but I haven't yet tested this against the particular failure mode.

fixes #970 TCP connections through docker-proxy do not reconnect

---

docs/CONTRIBUTING.adoc
docs/man/nng_ctx.5.adoc
docs/man/nng_dialer.5.adoc
docs/man/nng_listener.5.adoc
docs/man/nng_pipe.5.adoc
docs/man/nng_send.3.adoc
docs/man/nng_socket.5.adoc
include/nng/nng.h

This fixes some typos in the documentation that I noticed while learning how to use this great library. Since English is not my native language, I may be wrong in some cases - so just ignore my changes in this case.

fixes some typos in documentation

---

docs/man/nng_sub.7.adoc
include/nng/protocol/pubsub0/sub.h
src/protocol/pubsub0/pub.c
src/protocol/pubsub0/sub.c

This adds a new option (`NNG_OPT_SUB_PREFNEW`) that toggles whether SUB0 contexts ignore new messages when the queue is full or whether they drop an old message in order to make room.
This probably needs some work to be ready to merge into master, so I'm more than willing to make whatever changes necessary.

Add option to SUB0 protocol to prefer newer messages when queue is full

---

src/core/message.c
src/supplemental/websocket/websocket.c

It's possible for an empty chunk to have a NULL data pointer.
Even when copying zero bytes, this makes clang somewhat unhappy.

fixes #1004 Warning found by clang --analyze

---

src/supplemental/websocket/CMakeLists.txt

This PR fixes a build error when the `NNG_SUPP_WEBSOCKET` option is turned off.

Fix typo in websocket/CMakeLists.txt

---

src/supplemental/tls/CMakeLists.txt

If mbedTLS is added as a CMake target, this fix will handle it properly.

Add possibility to use mbedtls cmake target if available

---

docs/man/libnng.3.adoc
docs/man/nng_http_server_get_addr.3http.adoc
include/nng/supplemental/http/http.h
src/supplemental/http/http_public.c

When a http server is started with port zero, a port is automatically assigned. This PR just makes it possible to retrieve the port number.

Add http server method for getting port number

---

src/platform/windows/win_thread.c

When using the 32-bit Windows compiler, the functions
InterlockedIncrementAcquire64() and and InterlockedDecrementRelease64() are not
defined.  So we fall back to the more generic InterlockedAcquire64() and
InterlockedDecrement64() on 32-bit Windows.

Fixes broken win32 build.

---

src/compat/nanomsg/compat_tcp.c
src/protocol/reqrep0/rep.c
src/protocol/reqrep0/rep_test.c
tests/httpclient.c

This also significantly increases the test coverage for the REP protocol.

fixes #1099 Should inline backtrace buffer in REP

---

src/core/platform.h
src/core/pollable.c
src/core/pollable.h
src/platform/posix/posix_atomic.c
src/platform/windows/win_thread.c
src/protocol/pair1/pair.c
src/protocol/pubsub0/pub.c
src/protocol/pubsub0/sub.c
src/protocol/reqrep0/rep.c
src/protocol/reqrep0/rep_test.c
src/protocol/reqrep0/req.c
src/protocol/survey0/respond.c
src/protocol/survey0/survey.c

This also introduces an nni_atomic_cas64 to help with lock-free designs.
Some mechanical renaming was done in some of the protocols for spelling.

fixes #1105 pollable can be inlined, and use atomics

---

src/platform/posix/posix_ipc.h
src/platform/posix/posix_ipcconn.c
src/platform/posix/posix_ipcdial.c
src/platform/posix/posix_ipclisten.c
src/platform/posix/posix_pollq_epoll.c
src/platform/posix/posix_pollq_kqueue.c
src/platform/posix/posix_pollq_port.c
src/platform/posix/posix_resolv_gai.c
src/platform/posix/posix_tcp.h
src/platform/posix/posix_tcpconn.c
src/platform/posix/posix_tcpdial.c
src/platform/posix/posix_tcplisten.c
src/supplemental/tcp/tcp.c
src/supplemental/tls/mbedtls/tls.c

We reap the connections when closing, to ensure that the clean up is
done outside the pollq thread.  This also reduces pressure on the
pollq, we think.  But more importantly it eliminates some complex
code that was meant to avoid deadlocks, but ultimately created other
use-after-free challenges.  This work is an enabler for further
simplifications in the aio/task logic.

Changes to the posix poller to ensure that fini is always safe.

---

src/protocol/reqrep0/rep.c
src/protocol/reqrep0/xrep.c
src/protocol/survey0/respond.c
src/protocol/survey0/xrespond.c

Specifically, we don't need to read the atomic value each loop
iteration.  We can just get it when a message is first received,
and then use that value.  This should make receiving through proxies
a little more efficient.

TTL reads could be fewer.

---

src/supplemental/http/http_server.c
tests/httpserver.c

fixes #751 http server directory handler
The test `(uri[len] != '/')` fails on all URIs other than "/". This PR fixes this.

Fix URI test that fails on all non-base URIs

---

src/core/message.c
src/core/message.h
src/protocol/bus0/bus.c
src/protocol/pubsub0/pub.c
src/protocol/pubsub0/sub.c
src/protocol/reqrep0/req.c
src/transport/inproc/inproc.c

This introduces reference counting on messages to reduce the data copies.
This should have a marked improvement when moving large messages through
the system, or when publishing to many subscribers.  For inproc, when
using large messages, the copy time can be the dominant factor; for example
using REQ/REP over inproc with 1M messages, we saw latencies in the 100us+
range.  With this change, on the same hardware, the latencies dropped down
to around 28 us.
For this PR, we are going to want  to pay particular attention to the sanitizers. 
I think I've taken care to get this correct, but the proof will be in the pudding.

fixes #1156 Message cloning could help reduce copies a lot

---

src/compat/nanomsg/CMakeLists.txt
src/compat/nanomsg/compat_tcp_test.c
src/compat/nanomsg/compat_testutil.h
src/protocol/reqrep0/xreq_test.c
src/protocol/survey0/xsurvey_test.c
tests/testutil.c
tests/testutil.h

This only addresses the newly rewitten compat_tcp test, but it
sets the groundwork for the other tests, so that when they are
updated to the new acutest.h they can use the new marry code to
establish connections cleanly and safely.

fixes #1163 compat tests are very brittle

---

src/core/defs.h
src/core/message.c
src/protocol/pair1/pair.c
src/protocol/pair1/pair1_test.c
src/protocol/reqrep0/rep.c
src/protocol/reqrep0/req.c
src/protocol/reqrep0/req_test.c
src/protocol/reqrep0/xrep.c
src/protocol/reqrep0/xrep_test.c
src/protocol/reqrep0/xreq.c
src/protocol/reqrep0/xreq_test.c
src/protocol/survey0/respond.c
src/protocol/survey0/respond_test.c
src/protocol/survey0/survey.c
src/protocol/survey0/xrespond.c
src/protocol/survey0/xrespond_test.c
src/protocol/survey0/xsurvey.c
src/protocol/survey0/xsurvey_test.c

fixes #1160 Consider limiting maximum hop count to 15
fixes #1098 Maximum maxTTL should be compile time defined
This doesn't expose the max-MaxTTL in the CMakeList.txt -- there
is really no reason anyone should be changing it.  This does not
yet inline the message header into the nni_msg_t, but it is my
intention to do so soon, and eliminate most of the conditional cases
for failure on inserting into the header.

fixes #1169 survey and xsurvey could use message cloning

---

src/core/stats.c

fixes #1179 
Fix build error when 'NNG_ENABLE_STATS` is `OFF`

Fix stats build error.

---

docs/man/nng_pair.7.adoc
docs/man/nng_pair_open.3.adoc
include/nng/protocol/pair1/pair.h
src/protocol/pair1/CMakeLists.txt
src/protocol/pair1/pair1_poly.c
src/protocol/pair1/pair1_poly_test.c
src/protocol/pair1/pair1_test.c

See the bug report for details.
To use pair1 polyamorous mode after this, code has to be converted to use nng_pair1_open_poly().
Raw mode polyamorous sockets are not supported.
Full test coverage is included.  As a bonus, we've improved the coverage for pair1 itself.

fixes #1189 Extract and deprecate polyamorous mode

---

demo/async/client.c
demo/raw/raw.c

Issue: starting the client(s) first, and the server afterwards blocks communication in these demo samples.
Most error codes in `nng_errno_enum` are positve values, so the existing error check would not catch something like `NNG_ECONNREFUSED`, the execution would proceed, and the communication would get blocked.
With this change, if the server is not able to receive, the client would exit with `fatal` instead of hanging.

Fix error checks

---

CMakeLists.txt
src/core/taskq.c

This introduces a new CMake option, NNG_MAX_TASKQ_THREADS, with
a default value of 16.  The number of taskq workers will generally
be calculated as vcpu * 2.  This new value, if not zero, sets an
upper bound.  Note that the value should be at least two, in order
to ensure no deadlocks occur.

fixes #1202 More than 120 threads was started by NNG

---

docs/BUILD_CROSSCOMPILE.adoc

Nng is available as a port in vcpkg, a C++ library manager that simplifies installation for nng and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build nng, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and here is what the port script looks like. We try to keep the library maintained as close as possible to the original library.

Add Vcpkg instructions

---

src/protocol/reqrep0/rep.c
src/protocol/reqrep0/req.c
src/protocol/survey0/respond.c

This also affects the respondent protocol.  Examination of the other
protocols did not turn up any evidence of the same issue.

fixes #1241 SIGSEGV in RepReq's rep0 recv - use after free

---

docs/man/nng_cv_wait.3supp.adoc

`cv_wake` should be `nng_cv_wake`

fix typo in nng_cv_wait example

---

CMakeLists.txt
src/platform/posix/posix_ipcconn.c
tests/ipc.c

fixes #1255 macOS support for NNG_OPT_IPC_PEER_PID
`ipc_peerid` in posix_ipcconn.c uses `getpeereid` even on systems with the `LOCAL_PEERCRED` socket option. If `LOCAL_PEERCRED` is available, use it instead and allow retrieving the peer PID if `LOCAL_PEERPID` is available.
`LOCAL_PEERPID` is documented on macOS since 10.8. 
We assume anyone building nng on a Mac is using >10.8. At runtime, the option may still be available in the kernel depending on the macOS version, but otherwise, the existing behaviour is retained (return `NNG_ENOTSUP`)
Finally, the check for `LOCAL_PEERID` is elevated into `NNG_HAVE_LOCALPEERPID` so we can check in the ipc unit test.

Support NNG_OPT_IPC_PEER_PID on modern macOS systems

---

CMakeLists.txt

fixes printing to stderr causing other build tools to detect a build error.
The default mode for "message()" under default configuration prints to stderr, some build tools take this to mean an error has occurred incorrectly.

Print NNG configuring message to STATUS mode.

---

src/supplemental/tls/tls_common.c

This was first detected as a stack overrun, but in actuality the
problem could have lead to corruption of TLS messages due to
prematurely recording transmit completion.

fixes #1235 framing error in SSL/TLS

---

src/core/platform.h
src/platform/posix/posix_resolv_gai.c
src/platform/windows/win_resolv.c
src/supplemental/http/http_server.c
src/supplemental/tcp/tcp.c

fixes #1224 wss fails on IPV6 address
This fixes bugs and inconsistencies in the way addresses are
handled for HTTP (and consequently websocket).  The Host:
address line needs to look at numeric IPs and treat wildcards
as if they are not specified, and needs to understand the IPv6
address format using brackets (e.g. [::1]:80).

fixes #844 WebSocket wildcard host errors

---

CMakeLists.txt
src/platform/posix/posix_pollq_epoll.c
src/platform/posix/posix_pollq_kqueue.c

This was responsible for hangs in close on FreeBSD.  Apparently
our use of EVFILT_USER was incorrect, and rather than fix it, we
have switched to using a notification pipe for synchronizing
closing pipes. In addition to fixing this problem, it should
significantly improve things for NetBSD and OpenBSD, which will
now be able benefit from kqueue(), since we no longer depend on
EVFILT_USER.

fixes #1275 Test timeouts on FreeBSD

---

docs/RATIONALE.adoc

This is also missing in https://nng.nanomsg.org/RATIONALE.html, which seems to be a newer/extended version of this document

added missing backquote

---

docs/man/nng_ws.7.adoc
include/nng/nng.h
src/supplemental/websocket/websocket.c
src/supplemental/websocket/websocket_test.c

This adds new options, NNG_OPT_WS_SEND_TEXT and NNG_OPT_WS_RECV_TEXT
that permit communication with WebSocket peers that insist on using
TEXT frames (stream mode only).  The support is limited, as NNG does
no validation of the frame contents to check for UTF-8 compliance.

fixes #914 websocket stream mode should support TEXT

---

docs/man/CMakeLists.txt
docs/man/libnng.3.adoc
docs/man/nng_stat_bool.3.adoc
docs/man/nng_stat_string.3.adoc
include/nng/nng.h
src/core/dialer.c
src/core/listener.c
src/core/pipe.c
src/core/socket.c
src/core/sockimpl.h
src/core/stats.c
src/core/stats.h
src/protocol/pair1/pair.c
src/protocol/pair1/pair1_poly.c
src/transport/ipc/ipc.c
src/transport/tcp/tcp.c
src/transport/tls/tls.c

This should reduce the amount of copying, and the overall size
used by pipes and other objects quite a bit.  (On my system, the
sizeof nni_pipe shrank by 400 bytes, for example.)

fixes #1323 stats framework is *way* to heavy

---

docs/man/libnng.3.adoc
docs/man/nng_aio_free.3.adoc
include/nng/nng.h
src/core/aio.c
src/core/aio.h
src/core/aio_test.c
src/nng.c
src/supplemental/http/http_client.c

This also converts the HTTP client to make use of this.

fixes #1313 support deferred nng_aio destruction

---

src/core/aio.c
src/core/aio.h

This scales the aio lock into a one-per-CPU-core expiration list, including thread and lock.

fixes #1172 nni_aio_lk is white hot

---

src/platform/posix/posix_resolv_gai.c

I noticed the `tcpsupp` test was failing on OpenBSD as well as on my Alpine Edge (musl v1.2.2-pre6) vm I use. (Tests at the v1.3.2 tag all pass, however.)
Looking into the problem, I traced it to the fact the url in the test (`tcp://127.0.0.1`) eventually ends up parsed and transformed into a `resolve_item` where `serv` is a non-`NULL` pointer. This results in the service name argument in the `getaddrinfo(3)` call to be non-`NULL` (like `""`). Apparently this is acceptable on some POSIX-like platforms (e.g. glibc-based Linux).
However, if one calls getaddrinfo(3) on OpenBSD like so, it returns -8 (`EAI_NONAME`):
```c
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <string.h>
#include <stdio.h>
int main() {
struct addrinfo hints;
struct addrinfo *results;
int rv; …
```

getaddrinfo(3) on musl & BSDs fails with servname = ""

---

src/supplemental/http/http_server.c

fixes #1393 Use after free in http

fixes #1393 Use after free in http

---

src/supplemental/tls/tls_common.c

This fixes a build error when `NNG_TLS_ENGINE_INIT` is not defined.

Fix typo in tls_common.c

---

src/supplemental/tls/mbedtls/tls.c

Was looking into how to extend TLS support to a new engine when I found a small oddity.
The comment is an artifact from an old `tls_reap` function and no longer describes the following function (`conn_init`).
Function `conn_init` should be marked `static` as well to fit the design of the tls engine api and match the other mbed-related functions local to `src/supplemental/tls/mbedtls/tls.c`.

Remove extraneous/out-dated comment, declare conn_init static

---

src/platform/posix/posix_thread.c

OpenBSD requires an additional header for both `pthread_set_name_np` and `pthread_get_name_np`. Otherwise, you get compiler warnings like:
```
[43/399] Building C object CMakeFiles/nng.dir/src/platform/posix/posix_thread.c.o     
../src/platform/posix/posix_thread.c:274:3: warning: implicit declaration of function 'pthread_set_name_np' is invalid in C99 [-Wimplicit-function-declaration]
pthread_set_name_np(pthread_self(), name);                                                                                                                   
^                                                                     
../src/platform/posix/posix_thread.c:276:10: warning: implicit declaration of function 'pthread_set_name_np' is invalid in C99 [-Wimplicit-function-declaration] …
```

Fix implicit declaration warnings for pthread_set_name_np on OpenBSD

---

src/sp/protocol/pubsub0/sub.c

In case `sub0_ctx_subscribe` is called to subscribe to _all_ topics.
fixes #1436 Guard against UB in sub0_ctx_subscribe

fixes #1436 Guard against UB in sub0_ctx_subscribe

---

src/sp/transport/zerotier/zerotier.c

The message must remain intact for a possible future resent, otherwise a reqrep resent will end up in an loop sending an empty message and receiving a protocol error response.

Fix for ZeroTier transport

---

include/nng/nng.h
src/core/aio_test.c

This bug can easily lead to memory overruns if a program relies
on the nng_sockaddr_storage instad of just allocating a vanilla
nng_sockaddr.

fixes #1430 nng_sockaddr larger than nng_sockaddr_storage

---

src/core/aio.c
src/core/defs.h

When there are too many aios in the nni list, the efficiency of the ordered list decreases significantly.
Turn aio expire queue from ordered nni list to array will perform better.
The perf results in projects nanomq(forked from nng) are presented in following two xml file.
Test conditions.
+ 25k connections.
+ interval of connection is 6 seconds.
+ each test lasts about 3 minutes.
(Notes. xml format is not supported for attachments. so, i compress it with tar.)
[perf.tar.gz](https://github.com/nanomsg/nng/files/6357856/perf.tar.gz)

Turn aio expire queue from nni list to array for efficiency.

---

src/core/aio_test.c

GitHub's darwin server farm appears possibly overloaded, and
the timing specific checks in that environment appear to be busted.
Local instances of macOS don't seem to have problems though.

Disable clock-dependent checks on macOS in CI/CD.

---

src/core/platform.h
src/platform/posix/posix_impl.h
src/platform/posix/posix_thread.c
src/platform/windows/win_impl.h
src/platform/windows/win_thread.c
src/sp/transport.c

This provides the initial implementation, and converts the
transport lookup routines to use it.  This is probably of limited
performance benefit, but rwlock's may be useful in further future work.

fixes #1409 reader/writer lock desired

---

CMakeLists.txt

Static libs generated on iOS, tvOS or watchOS are missing several symbols. The build succeeds, but static lib is illformed, and link of application to this lib will likely fail.
The reason is that proper definitions are injected only for macOS (if I look into source code, `NNG_PLATFORM_POSIX` is important, and `NNG_PLATFORM_DARWIN` useless). Indeed, `CMAKE_SYSTEM_NAME` is not `Darwin` if cross-building to iOS/tvOS/watchOS.
Instead of repeating `CMAKE_SYSTEM_NAME MATCHES "Darwin"`, `CMAKE_SYSTEM_NAME MATCHES "iOS"` etc, there is `APPLE` variable: https://cmake.org/cmake/help/latest/variable/APPLE.html

CMake: fix cross-build to iOS/tvOS/watchOS

---

src/platform/posix/posix_pollq_epoll.c

I am trying to replace ZeroMQ with NNG in some company libraries. In our UTs I have added `nng_fini()` to our `atexit()` to avoid false positives reported by valgrind regarding possible lost bytes. One thing I cannot get rid of however is this error
```
==1664== Syscall param epoll_ctl(event) points to uninitialised byte(s)
==1664==    at 0x4D527BE: epoll_ctl (syscall-template.S:78)
==1664==    by 0x49660D8: nni_posix_pfd_arm (in /usr/lib/i386-linux-gnu/libnng.so.1)
==1664==    by 0x495FACF: ipc_listener_doaccept (in /usr/lib/i386-linux-gnu/libnng.so.1)
==1664==    by 0x4960799: ipc_listener_accept (in /usr/lib/i386-linux-gnu/libnng.so.1)
==1664==    by 0x49584EA: nng_stream_listener_accept (in /usr/lib/i386-linux-gnu/libnng.so.1)
==1664==    by 0x497B3FF: ipc_ep_accept (in …
```

Fix valgrind error epoll_ctl points to uninitialised bytes

---

docs/man/nng_inproc_register.3.adoc
docs/man/nng_ipc_register.3.adoc
docs/man/nng_tcp_register.3.adoc
docs/man/nng_ws_register.3.adoc
docs/man/nng_wss_register.3.adoc
docs/man/nng_zt_register.3.adoc
include/nng/transport/inproc/inproc.h
include/nng/transport/ipc/ipc.h
include/nng/transport/tcp/tcp.h
include/nng/transport/tls/tls.h
include/nng/transport/ws/websocket.h
include/nng/transport/zerotier/zerotier.h
src/sp/transport.c
src/sp/transport/inproc/inproc.c
src/sp/transport/ipc/ipc.c
src/sp/transport/tcp/tcp.c
src/sp/transport/tls/tls.c
src/sp/transport/ws/websocket.c
src/sp/transport/zerotier/zerotier.c

Originally the idea was to better support having the transports
be separate loadable modules.  This isn't needed for the builtin
transports, so we make the explicit initialization of them
deprecated, and document it as such.

Fix premature transport registration. Mark it deprecated.

---

src/core/init.c
src/core/protocol.c
src/core/protocol.h

Nothing is using this, but it adds complexity and also requires
additional lock activity each time a socket is opened.

Remove separate protocol initialization step.

---

cmake/FindmbedTLS.cmake
src/supplemental/tls/mbedtls/tls.c
src/supplemental/tls/tls_common.c
src/supplemental/tls/tls_test.c
tests/tls.c
tests/trantest.h

This adds support for mbedTLS 3.0.  Note that there are some limitations because mbedTLS 3.0 doesn't support some of the older algorithms or protocols or options.

fixes #1478 mbedTLS 3.0 is not API compatible with 2.x

---

src/core/aio.c
src/core/aio.h
src/core/defs.h

There were several problems with the array implementation, both
from performance and from correctness.  This corrects those errors
(hopefully) and restores the expiration lists as linked lists.

fixes #1488 aio expiration list performance work needed

---

src/core/pipe.c
src/core/socket.c
src/core/sockimpl.h

This eliminates several mutex operations done each time a pipe
is created or destroyed.  For large scale systems this should
reduce overall pressure on the memory subsystem, and scale better
as many threads are coming and going.
This also reduces the overall size of nni_pipe -- on Linux by
36 bytes typically.

Eliminate the pipe mutex and use atomic for pipe closed.

---

src/tools/perf/perf.c
src/tools/perf/pubdrop.c

When building with PAIR and PUBSUB protocols disabled, the perf tools fail to compile.
This makes some minor tweaks to correct that

fix building with PAIR and PUBSUB disabled

---

src/platform/posix/posix_config.h
src/testing/marry.c

This makes CLOCK_MONOTONIC the default (as it should have been)
for platforms that have it defined, except for Apple platforms which lack
support for using anything other than the real time clock with condition
variables.  (And unfortunately silently ignore attempts to do otherwise.)

fixes #1526 NNG_USE_CLOCKID Bug?

---

src/core/platform.h
src/platform/posix/posix_atomic.c
src/platform/posix/posix_impl.h
src/platform/windows/win_impl.h
src/platform/windows/win_thread.c
src/supplemental/tls/tls_common.c

This is initially used for TLS to make loading the engine pointer
faster, eliminating a much more expensive lock operation.

Provide atomic pointer support.

---

src/core/dialer.c
src/core/idhash.h
src/core/init.c
src/core/init.h
src/core/list.h
src/core/listener.c
src/core/socket.c
src/core/stats.c
src/platform/posix/posix_impl.h
src/platform/posix/posix_thread.c
src/platform/windows/win_impl.h
src/platform/windows/win_thread.c
src/sp/transport.c
src/supplemental/http/http_client.c
src/supplemental/http/http_server.c
src/supplemental/tls/tls_common.c

This eliminates some run-time initialization, moving it to compile time.
Additional follow up work will expand on this to simplify initialization
and reduce the need for certain locks.

Use static initialization for lists and mutexes.

---

src/platform/windows/win_impl.h
src/platform/windows/win_thread.c

- Use correct datatype for one nni_atomic_flag (that hadn't been changed to LONG)
- resolves a compiler warning
- Use InterlockedExchangeAdd instead of InterlockedAdd (which isn't implemented on 32-bit windows)

Fixes compiling on windows 32-bit

---

src/core/defs.h
src/platform/posix/posix_atomic.c
src/platform/posix/posix_impl.h

This should help greatly with performance on older systems such
as CentOS 7 and GCC 4.8.  Though, such folks really should update
to newer compilers.  Folks running version of GCC earlier than 4.7
will still pay a rather significant performance penalty, as they
still implement atomics with a global mutex.

Could use GCC atomics for older versions of GCC.

---

src/core/lmq.c
src/sp/protocol/bus0/bus.c

This ultimately makes the code for bus a little faster, and leads us in the direction where socket initialization might ultimately become non-failing (so we can can eliminate a failure case).  A few more cleanups needed for that first however.

Bus aio's can be inline.

---

src/core/msgqueue.c
src/core/pollable.c
src/core/pollable.h
src/sp/protocol/pubsub0/pub.c

This eliminates more failure paths, and brings us still closer
to eliminating the possibility of failure during socket init.

Pollables can be completely inline.

---

include/nng/nng.h

defines a NNG_DEPRECATED macro that will emit the deprecated attribute supported by GCC & Clang
Add this macro to all deprecated functions

mark deprecated functions as deprecated so they show as warnings during compile

---

src/core/message_test.c
src/core/sock_test.c
src/sp/protocol/bus0/bus_test.c
src/sp/protocol/pair0/pair0_test.c
src/sp/protocol/pair1/pair1_poly_test.c
src/sp/protocol/pair1/pair1_test.c
src/sp/protocol/pipeline0/push_test.c
src/sp/protocol/reqrep0/req_test.c
src/sp/protocol/survey0/respond_test.c
tests/device.c
tests/ipc.c
tests/multistress.c
tests/nonblock.c
tests/pipe.c
tests/pollfd.c
tests/reqctx.c
tests/scalability.c
tests/stats.c
tests/tcp.c
tests/tcp6.c
tests/tls.c
tests/trantest.h
tests/ws.c
tests/wss.c
tests/zt.c

This updates (most) tests to not use deprecated function.
There are only two remaining calls to nng_closeall() that remain.  Not sure how you want to handle those two

Feat cleanup deprecated usage in tests

---

src/core/aio.c
src/core/aio.h
src/platform/posix/posix_ipcdial.c
src/platform/posix/posix_resolv_gai.c
src/platform/posix/posix_tcpdial.c
src/platform/windows/win_resolv.c
src/platform/windows/win_tcpdial.c
src/platform/windows/win_tcplisten.c
src/supplemental/http/http_conn.c
src/supplemental/websocket/websocket.c

This takes one less parameter, and is simpler.  It will let us
reclaim the aio_prov_extra data space as well, so that we can
use it for other purposes.

Replace nni_aio_prov_set_extra with nni_aio_prov_set_data.

---

docs/man/libnng.3.adoc
docs/man/nng_aio_alloc.3.adoc
docs/man/nng_aio_busy.3.adoc
docs/man/nng_aio_wait.3.adoc
include/nng/nng.h
src/core/aio.c
src/core/aio.h
src/core/aio_test.c
src/core/taskq.c
src/core/taskq.h
src/nng.c

This introduces a new API, nng_aio_busy(), that can be used
to query the status of the aio without blocking.
Some minor documentation fixes are included.

fixes #1574 Non-blocking version of nng_aio_wait / nng_aio_result

---

src/platform/posix/posix_atomic.c

fixes #1586 Undefined reference to nni_atomic_swap & nni_atomic_cas ( Built by gcc 4.8.5 )

fixes #1586 Undefined reference to nni_atomic_swap & nni_atomic_cas

---

src/platform/windows/win_thread.c

fixes https://github.com/nanomsg/nng/issues/1590

fixes #1590 Undefined reference to nni_atomic_dec & nni_atomic_dec64 on Windows.

---

src/supplemental/http/http_server.c

fixes #1594 undefined behaviour due to out-of-bounds in http_uri_canonify().
A small, but important change was done in http_uri_canonify() to mend the issue.

Fix out-of-bounds error in http_uri_canonify().

---

src/core/socket.c

The socket member `st_name` is not available when NNG_ENABLE_STATS is OFF.

Fixes compiling when NNG_ENABLE_STATS is OFF

---

src/platform/windows/win_tcplisten.c

From the [docs](https://docs.microsoft.com/en-us/windows/win32/api/mswsock/nf-mswsock-acceptex), this function requires as a parameter the listener socket, not a boolean value.
With this change, `shutdown` now can start the socket closing process correctly.
fixes #1598

Fixes the call to setsockopt(SO_UPDATE_ACCEPT_CONTEXT) on Windows (#1598)

---

src/core/defs.h

fixes #1621 Silence NNI_ASSERT warnings

Silence NNI_ASSERT warnings when building with NDEBUG (#1621)

---

src/core/idhash.c

Fix for UBSAN error, such as excerpt below:
```
idhash.c:132:14: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:44:28: note: nonnull attribute specified here
```
As `id_reg_map` is initialised as NULL and passing NULL to `memcpy()` is undefined. Should make no difference to compiled code. Purely to appease the automated checks I have to deal with on my side. Thanks!

Fix UBSAN error in idhash.c

---

src/sp/protocol/pair0/pair.c

This function needs to be pretty much identical between PAIR v0 and v1, it was missing just the call to release the pollable resources.
I was testing the compat API and i discovered that when using PAIR v0, it was leaking file descriptors because of this. This solves the problem completely mirroring the same logic present in PAIR v1 (https://github.com/nanomsg/nng/blob/master/src/sp/protocol/pair1/pair.c#L79-L80).

Fix PAIR v0 not finalizing the pollables when closing socket

---

src/core/aio.c

fixes #1543 by aborting tasks that may have been prepped, but not yet started. otherwise on a socket close the reap thread can get stuck waiting for the task to start/finish.

fixes issue #1543 - Deadlock in nng_close(socket)

---

src/sp/transport/tcp/tcp.c

Issue:
I use bus protocol on tcp. Programm some times hangs on closing socket.
This change fixes hangs on socket close. I saw hang with bus protocol on close from time to time. It hangs in bus0_pipe_stop() on nni_aio_stop(&p->aio_recv); As I found protocol's aio calls on stopping tcptran_pipe_recv_cancel() that should remove it from tcp->recvq, but tcp->rxaio is stopped at that time by tcp close function. As I understand tcptran_pipe_recv_cb() some times is called in between of setting up closed flag and real stopping of tcp->rxaio. This change should fix handling of this scenario

src: sp: tcp: Finish receive aio on close

---

docs/man/nng_tls.7.adoc
docs/man/nng_tls_options.5.adoc
docs/man/nng_ws.7.adoc
include/nng/nng.h
include/nng/supplemental/tls/engine.h
src/supplemental/tls/mbedtls/tls.c
src/supplemental/tls/tls_common.c

When doing TLS client authentication, the TLS server may need to query the common name of the client.
Example:
```
nng_socket sock;
nng_msg *msg;
nng_pipe p;
char * cn;
nng_recvmsg(sock, &msg, 0);
p = nng_msg_get_pipe(msg);
nng_pipe_get_string(p, NNG_OPT_TLS_PEER_CN, &cn);
printf("peer CN: %s\n", cn);
free(cn);
```

Get common name and subject alternative names of peer certificate

---

src/platform/posix/posix_resolv_gai.c

Borrowed from: https://github.com/macports/macports-legacy-support/blob/2806f66dbd0a7a47fb97fda5f9caedbac4b5f18b/include/netdb.h#L28-L30

posix_resolv_gai.c: add AI_NUMERICSERV where undefined

---

CMakeLists.txt

NNG_MAX_EXPIRE_THREADS docs say that 0 means unlimited, but there is a code check that imposes a limit between [1, 256].
This commit fixes the doc.

fixes #1683 NNG_MAX_EXPIRE_THREADS tunable documentation

---

demo/pubsub_forwarder/CMakeLists.txt
demo/pubsub_forwarder/README.adoc
demo/pubsub_forwarder/pubsub_forwarder.c

This provides a demo for using nng_device to create a forwarder or proxy.

Add forwarder demo

---

src/supplemental/http/http_server.c
tests/httpserver.c

When serving a directory, an URI such as `http://127.0.0.1/flutter_service_worker.js?v=666216136` will fail because the HTTP server thinks the URI parameter is part of the filename. This PR drops the URI parameters when serving a directory.

Skip URI parameters when serving a directory (http_server)

---

docs/man/nng_thread_set_name.3supp.adoc

function name was wrong in the code snippet.

fix typo in nng_thread_set_name doc

---

CMakeLists.txt
src/core/aio.c

This change makes expire threads tunable follows the same strategy as taskq threads tunables.
Add NNG_NUM_EXPIRE_THREADS to override the default behavior (`n_cpu` expire threads).
The NNG_MAX_EXPIRE_THREADS limit is always applied if > 0, even if you specify the desired number of threads using NNG_NUM_EXPIRE_THREADS.
NNG_EXPIRE_THREADS is not used anymore. This was only referenced in the code but never defined on CMake.
The logic to cap expire threads between 1 and 256 was removed. If users set no limits, whatever value they choose will be used instead of being silently overridden by us.

fixes #1619 expose expire threads tunables

---

src/platform/posix/posix_ipcdial.c
src/platform/posix/posix_tcpdial.c

(This also affects TCP, and fixed there.)

fixes #1675 undefined behavior in posix ipc_dialer_dial

---

src/core/dialer.c
src/core/listener.c
src/core/panic.c
src/core/pipe.c
src/sp/protocol/pair1/pair.c

fixes warnings or build error when macros are undefined or set to `0`
When they are set to `0`, nng does not even build due to undefined references.
When they are unset, we get many warnings, like:
```
nng/src/core/panic.c:26:5: warning: "NNG_HAVE_BACKTRACE" is not defined, evaluates to 0 [-Wundef]
26 | #if NNG_HAVE_BACKTRACE
```
This fixes by using `ifdef` everywhere, so we don't get any warnings when the macros are not set.

Normalize ifdef macro handlings for configs

---

src/sp/protocol/reqrep0/req.c

req: use nni_aio_completions - this is similar to #1523

---

src/sp/transport/inproc/inproc.c
src/sp/transport/ipc/ipc.c
src/sp/transport/tcp/tcp.c
src/sp/transport/tls/tls.c
src/sp/transport/ws/websocket.c
src/sp/transport/zerotier/zerotier.c

fixes #1713 SP pipe_send leaks message if aio is canceled

---

src/supplemental/tls/tls_common.c

The aio for connections was meant to have an infinite sleep (no timeout), but was getting an initial value of zero, so we were spinning on accept.

fixes #1673 High CPU usage with TLS

---

docs/man/nng_req.7.adoc
include/nng/protocol/reqrep0/req.h
src/compat/nanomsg/nn.c
src/sp/protocol/reqrep0/req.c
src/sp/protocol/reqrep0/req_test.c

This eliminates the req protocols use of nni_timer (and setting a single timer node per request.  This was problematic because it devolves into O(n^2) as we wind up inserting timer nodes and having to scan the list for the timer node.
The solution is to use a single scan - stop worrying about insertion, but instead use a coarse granularity timer (defaults to 1 second) for retries.  Then do the O(n) scan just once per interval.
(For now the tick interval for this is fixed at one second, but I intend to follow up with a change to make an option.)

fixes #1663 Request/Reply Protocol Throughput and Scalability

---

src/supplemental/http/http_api.h
src/supplemental/http/http_server.c
src/supplemental/websocket/websocket.c

This fixes two hangs on teardown (separate - one in the lister, and one in the dialer), and resolves the RFC 6455 conformance issue for WS_CLOSE frames.

Various websocket fixes

---

cmake/NNGOptions.cmake
docs/man/CMakeLists.txt
docs/man/libnng.3.adoc
docs/man/nng_id_map.3supp.adoc
src/core/dialer.c
src/core/id_test.c
src/core/idhash.c
src/core/idhash.h
src/core/listener.c
src/core/pipe.c
src/core/socket.c
src/sp/protocol/reqrep0/req.c
src/sp/protocol/survey0/survey.c
src/supplemental/idhash/CMakeLists.txt
src/supplemental/idhash/idhash.c
src/supplemental/idhash/idhash.h
src/supplemental/idhash/idhash_test.c

This includes a manual page documenting the entire set of functions in one step.  The hash is 64-bit based for now, to be maximally flexible.  An internal 32-bit convenience for the common internal use is also provided (not public).
The public API includes a test suite.

fixes #1740 Public ID hash API

---

CMakeLists.txt
src/platform/windows/win_io.c

This (defaults to 8) sets a limit on the number of poller threads that will be used for servicing I/Os.  This is the size of the I/O completion port thread pool on Windows.  POSIX pollers are generally not concurrent at present.

provide NNG_MAX_POLLER_THREADS

---

docs/man/nng_aio_set_timeout.3.adoc
docs/man/nng_clock.3supp.adoc
include/nng/nng.h
include/nng/supplemental/util/platform.h
src/core/aio_test.c
src/nng.c

While here fixed a number of nits in comments.

fixes #1751 Support nng_aio_set_expire().

---

CMakeLists.txt
include/nng/nng.h
src/core/CMakeLists.txt
src/core/aio.c
src/core/init.c
src/core/init.h
src/core/init_test.c
src/core/options.h
src/core/taskq.c
src/nng.c
src/platform/posix/posix_resolv_gai.c
src/platform/windows/win_io.c
src/platform/windows/win_resolv.c

This further limits some of the thread counts, but principally it offers a new runtime facility, nng_init_set_parameter(), which can be used to set certain runtime parameters on the number of threads, provided it is called before the rest of application start up.
This facility is quite intentionally "undocumented", at least for now, as we want to limit our commitment to it.  Still this should be helpful for applications that need to reduce the number of threads that are created.

fixes #1572 nng creates too many threads

---

demo/stream/CMakeLists.txt
demo/stream/platform/posix/server.c
demo/stream/platform/windows/server.c
demo/stream/stream.c

This PR adds a nng_stream example that connects to an arbitrary socket. Either start a new server with `./stream -s <portnumber>` or connect to an existing one using `./stream -c <url>`

Add a nng_stream example paired with a socket server on win/linux

---

src/sp/protocol/reqrep0/rep_test.c
src/testing/marry.c

This also adds a HUGE test for REP using socket so that we can discriminate failures that might exist using sockets instead of inproc.

Add support for socket:// in NUTS marry function.

---

cmake/FindMbedTLS.cmake

The old MBEDTLS_ROOT_DIR is still honored for legacy compat, but the version 4.3 find script won't use it by default.

build: Mbed TLS should use MBEDTLS_ROOT first.

---

src/platform/windows/win_ipcconn.c
src/platform/windows/win_tcpconn.c

This looks like a possible problem that may be windows specific involving the flow for IO completion ports.  This simplifies the logic a little bit, and should ensure that canceled requests on pipes do not restart.

fixes #1543 Deadlock in nng_close(socket)

---

CMakeLists.txt
cmake/NNGOptions.cmake
src/core/stream.c
src/platform/posix/CMakeLists.txt
src/platform/posix/posix_resolv_gai.c
src/platform/posix/posix_sockaddr.c
src/platform/posix/posix_tcpdial.c
src/platform/posix/posix_tcplisten.c
src/platform/resolver_test.c
src/platform/windows/win_resolv.c
src/platform/windows/win_sockaddr.c
src/platform/windows/win_tcpdial.c
src/sp/protocol.c
src/sp/transport/tcp/tcp.c
src/sp/transport/tls/tls.c
src/sp/transport/ws/websocket.c
src/testing/marry.c
tests/udp.c

This also checks if the build system has the definitions for AF_INET6, which might help in some embedded IPv4 only settings.
The resolver test is enhanced to include a check for IPv6 enabled in the kernel.
IPv6 support is enabled by default, of course.

fixes #1496 Provide NNG_ENABLE_IPV6 option (disabled by default)

---

src/platform/posix/posix_rand_getrandom.c

fixes #1804 Missing Header in posix_rand_getrandom.c
Can confirm that cross-compilation succeeds afterwards: https://github.com/r-universe/shikokuchuo/actions/runs/8639056802/job/23684720195#step:5:507

Add header to posix_rand_getrandom.c

---

src/supplemental/tls/tls_common.c

Add the missing stub function implementation for `nng_tls_config_hold()`. Fixes an error when loading the library and expecting to have this symbol available.
Build with `-DBUILD_SHARED_LIBS=ON`
The availability of the symbol can be checked with nm:
```
nm -D cmake-build-release/libnng.so.1.7.3  | grep nng_tls_config_hold
```

Add missing `nng_tls_config_hold` stub function

---

src/sp/transport/ipc/ipc.c
src/sp/transport/tcp/tcp.c
src/sp/transport/tls/tls.c

Also while here, remove unused sockaddr members from some structs. This should save a bit of memory for servers with a lot of conns.

Log messages when peer sends too large message.

---

src/core/message.c
src/core/message_test.c

With specific message sizes, we the shuffle of data for msg insert can calculate the wrong value, leading to heap corruption. This includes a stress test for msg insert to hopefully exercise every reasonable edge case.

fixes #1808 nng_msg_insert: munmap_chunk(): invalid pointer

---

src/core/aio.c

when an `aio` has no `a_cancel_fn` and the task is in `task_prep`state abort it on `nni_aio_stop` call
fixes #1813 Deadlock during nng_close() - multi platform

macOS - fix deadlock on reqrep socket close

---

src/sp/transport/zerotier/zerotier.c

Fixes problem that causing it unable to pass compile when NNG_TRANSPORT_ZEROTIER is enabled.
It seems that there are typo in the struct type naming. And the wrong function name in `nni_sp_zt_register` that will cause link error.

Fixes typo that will cause error when comipling zerotier transport.

---

tests/convey.c

fix testcase crash on NUTTX When log_buf is null for the first time.
Then the memcpy params will be null which cause crash.

fix testcase crash on NUTTX When log_buf is null for the first time.

---

docs/man/nng_id_map.3supp.adoc
include/nng/supplemental/util/idhash.h
src/core/idhash.c
src/core/idhash.h
src/supplemental/util/idhash.c
src/supplemental/util/idhash_test.c

This allows an efficient way to iterate over the entries stored in an ID hash. The iteration is fast, and requires no additional storage.  The order of iteration is not guaranteed.

idhash: add nng_id_visit API

---

src/platform/windows/win_ipcconn.c
src/platform/windows/win_tcp.h
src/platform/windows/win_tcpconn.c

trial to fix winipc crash

---

.github/workflows/windows.yml
src/core/log.c
src/supplemental/tls/mbedtls/tls.c
src/supplemental/tls/tls_test.c
src/supplemental/websocket/wssfile_test.c

This requires using a supporting version of Mbed TLS. We have to use PSA crypto for TLS 1.3.

TLS: enable TLS 1.3 for Mbed TLS.

---

README.adoc

fix link to TLS build instructions file. It was renamed from docs/BUILD_TLS.adoc to docs/BUILD_TLS.md in commit 6e5cf29

fix broken link to BUILD_TLS

---

src/platform/windows/win_ipclisten.c
src/platform/windows/win_tcpconn.c

Resulting from latest changes in #1828 and #1848 affecting the Windows platform only.
Eliminates `-Wint-to-pointer-cast` and `-Wmaybe-uninitialized` warnings. Commits should be self-explanatory.

Fixes Compiler Warnings (Windows)

---

src/platform/posix/CMakeLists.txt
src/platform/posix/posix_rand_getentropy.c

XPG8 defines getentropy() as the only good source for random numbers. However, real world use a bit more nuanced.  On BSD systems, we would prefer to use arc4random as it avoids unnecessary system calls.  On Linux however, getentropy is implemented in terms of getrandom, and should be used directly when available.

posix: add getentropy() based RNG

---

.github/workflows/coverage.yml
.github/workflows/darwin.yml
.github/workflows/linux.yml
.github/workflows/windows.yml

Bump checkout action to v4.

---

src/core/defs.h
src/core/taskq.h
src/sp/transport/CMakeLists.txt

Actually enable UDP.  Also fix some UWYI includes.

---

src/core/aio_test.c

Actually this test appears to be broken everywhere, and the only reason it ever worked is that we took > 50 ms to context switch.

fix aio test failures on darwin

---

.github/workflows/coverage.yml
src/core/aio.c
src/core/socket.c
src/sp/transport.c

Bump codecov to v4

---

include/nng/nng.h
src/sp/transport/udp/udp.c

UDP: add some statistics

---

docs/migrating/nng1.md
docs/ref/api/stats.md
include/nng/nng.h
src/core/list.h
src/core/stats.c
src/core/stats_test.c
src/sp/protocol/bus0/bus_test.c
src/sp/protocol/pair0/pair0_test.c
src/sp/protocol/pair1/pair1_poly_test.c
src/sp/protocol/pair1/pair1_test.c
src/sp/protocol/pipeline0/pull_test.c
src/sp/protocol/pipeline0/push_test.c
src/sp/protocol/pubsub0/pub_test.c
src/sp/protocol/pubsub0/sub_test.c
src/sp/protocol/pubsub0/xsub_test.c
src/sp/protocol/reqrep0/rep_test.c
src/sp/protocol/reqrep0/req_test.c
src/sp/protocol/reqrep0/xrep_test.c
src/sp/protocol/reqrep0/xreq_test.c
src/sp/protocol/survey0/respond_test.c
src/sp/protocol/survey0/survey_test.c
src/sp/protocol/survey0/xrespond_test.c
src/sp/protocol/survey0/xsurvey_test.c

This should help the compiler enforce checks, and may result in better optimizations.

Use `const` for nng_stat when possible.

---

src/core/defs.h

Essentially, we forgot to dereference as uint8_t *, which can lead to some suprises if these are misused.

NNI_GETXX macros are brittle due to casting mistake.

---

docs/ref/migrate/nanomsg.md
docs/ref/migrate/nng1.md
include/nng/protocol/pubsub0/sub.h
src/core/socket.c
src/core/socket.h
src/sp/protocol/pubsub0/pub_test.c
src/sp/protocol/pubsub0/sub.c
src/sp/protocol/pubsub0/sub_test.c
src/sp/protocol/pubsub0/xsub_test.c
src/tools/nngcat/nngcat.c
src/tools/perf/pubdrop.c
tests/multistress.c

The main purpose is to eliminate the NNI_TYPE_OPAQUE options, by putting these into their own first class, protocol-specific, functions.

Replace NNG_OPT_SUB_SUBSCRIBE/UNSUBSCRIBE with functions.

---

docs/ref/migrate/nng1.md
src/core/socket.c

The framework for saving and replaying socket options was left over, and should not be used.  But we do need to send the initial socket options to endpoints when creating them, so we have support for that in a cleaner fashion that does not require memory allocations.

Socket option handling clean ups for endpoints.

---

src/sp/transport/udp/udp.c
src/sp/transport/udp/udp_tran_test.c

Adds test cases for this and for remote pipe as well.

UDP: prefer new packets (drop older)

---

src/core/socket.c

It turns out that for now this results in early wakeups, due to another bug in the aio framework.  But when that bug is fixed, this bug will lead to hangs when redialing.
(cherry picked from commit 2dfb99506142f2d59bcc0e0fa7db6b19a3c75d43)

Integer sign extension bug in socket.c.

---

.github/workflows/linux.yml
cmake/FindwolfSSL.cmake

Add matrix of TLS engines, including wolfSSL

---

src/sp/transport/ws/ws_test.c
src/supplemental/tls/tls_common.c
src/supplemental/websocket/wssfile_test.c

This also covers a few test cases that we were missing.

websocket: Do not allow a listener or dialer to change TLS while running

---

docs/man/nng_tls_config_version.3tls.adoc
docs/ref/migrate/nng1.md
include/nng/nng.h
src/supplemental/tls/mbedtls/tls.c
src/supplemental/tls/tls_test.c
src/supplemental/tls/wolfssl/wolfssl.c

Those old algorithms are not used anywhere, and are not recommended. TLS 1.2 support has been prevalent for over a decade.

tls: remove support for TLS 1.0 and 1.1.

---

src/supplemental/tls/tls_test.c
src/testing/certs.c
src/testing/nuts.h

tls: add ecdsa test case

---

docs/man/nng_options.5.adoc
docs/ref/migrate/nanomsg.md
docs/ref/migrate/nng1.md
include/nng/nng.h
src/core/sock_test.c
src/core/socket.c
src/core/stats_test.c

This functionality was provided principally for libnanomsg compatibility. This saves some memory and eliminates some pointless functionality.
While here, updated the socket options documentation to remove references to options already removed.

remove NNG_OPT_SOCKNAME (and socket names altogether)

---

docs/ref/migrate/nanomsg.md
docs/ref/migrate/nng1.md
src/sp/transport/tcp/tcp.c
src/sp/transport/tcp/tcp_test.c
src/sp/transport/tls/tls.c
src/sp/transport/tls/tls_tran_test.c

This was an undocumented capability provided for libnanomsg.  The correct way to obtain the same functionality is to use `NNG_OPT_LOCADDR`.

tcp/tls: Remove support for local interface address in dialer URLs

---

docs/ref/api/url.md
docs/ref/migrate/nng1.md
include/nng/nng.h
src/core/platform.h
src/core/tcp.c
src/core/url.c
src/core/url.h
src/core/url_test.c
src/platform/posix/posix_resolv_gai.c
src/platform/resolver_test.c
src/platform/windows/win_resolv.c
src/sp/transport/tcp/tcp.c
src/sp/transport/tls/tls.c
src/sp/transport/udp/udp.c
src/supplemental/http/http_msg.c
src/supplemental/http/http_server.c

intern URL scheme

---

docs/ref/api/url.md
docs/ref/migrate/nng1.md
docs/ref/xref.md
include/nng/nng.h
src/core/dialer.c
src/core/listener.c
src/core/sockimpl.h
src/core/url.c
src/core/url.h
src/core/url_test.c
src/nng.c
src/platform/posix/posix_resolv_gai.c
src/platform/windows/win_resolv.c
src/sp/transport/socket/sockfd.c
src/sp/transport/tcp/tcp_test.c
src/sp/transport/tls/tls_tran_test.c
src/sp/transport/udp/udp_tran_test.c
src/sp/transport/ws/ws_test.c
src/supplemental/http/http_msg.c

Nng url no alloc

---

docs/man/nng_tls_config_own_cert.3tls.adoc
docs/ref/migrate/nng1.md
docs/ref/xref.md
src/sp/transport/tls/tls_tran_test.c
src/supplemental/tls/mbedtls/tls.c
src/supplemental/tls/tls_common.c

Tls mutual test

---

docs/man/nng_ctx_get.3.adoc
docs/man/nng_ctx_set.3.adoc
docs/man/nng_socket_get.3.adoc
docs/man/nng_socket_set.3.adoc
docs/ref/migrate/nng1.md
include/nng/nng.h
src/nng.c
src/supplemental/util/options_test.c

option parser: test for no clustering support

---

docs/man/nng_http_req_get_header.3http.adoc
docs/man/nng_http_req_get_method.3http.adoc
docs/man/nng_http_req_get_uri.3http.adoc
docs/man/nng_http_req_get_version.3http.adoc
docs/man/nng_http_res_get_header.3http.adoc
docs/man/nng_http_res_get_reason.3http.adoc
docs/man/nng_http_res_get_status.3http.adoc
include/nng/supplemental/http/http.h
src/supplemental/http/http_api.h
src/supplemental/http/http_msg.c
src/supplemental/http/http_public.c

http: constify some functions

---

src/sp/transport/socket/sockfd.c
src/sp/transport/tls/tls.c

Tls no extra resolver

---

src/core/init_test.c
src/supplemental/http/http_server.c

Http server race

---

src/platform/windows/win_ipclisten.c

This hopefully addresses a long standing bug with Windows IPC sometimes hanging on shut down.

windows ipc: check the return value of nni_aio_schedule

---

src/core/sockfd.c

This fixes a possible failure condition on teardown.

sockfd: check the result of nni_aio_schedule

---

src/core/CMakeLists.txt
src/core/nng_impl.h
src/core/pipe.c
src/core/refcnt.c
src/core/refcnt.h
src/core/sockimpl.h

This starts by using this for the nni_pipe, but we will use it for the other primary objects as well.  This should simplify the tear down and hopefully eliminate some races.
It does mean that pipe destruction goes through an additional context switch, for now at least.  This shouldn't be on the hot data path anyway.

fixes #1408 Reference count as a first class type

---

src/core/aio.c
src/core/aio.h
src/core/aio_test.c
src/core/init.c
src/core/reap.c
src/core/reap.h
src/core/taskq.c
src/core/taskq.h
src/platform/windows/win_ipcdial.c

Aio reap noreschedule

---

src/core/reap.c

reap: thread exits prematurely after reinitialization

---

src/core/aio.c
src/core/aio.h

Operations that might be performed during teardown, such as reaping, waiting, closing, freeing, should only be done if the aio has properly been initialized.  This is important for certain simple cases where inline aio objects are used, and initialization of an outer object can fail before the enclosed aio is initialized.

aio: make sure aio is initialized before certain operations

---

src/core/socket.c
src/core/socket.h
src/nng.c
src/sp/protocol/pubsub0/sub.c

Once a context has started the process of close, further attempts to close it will return NNG_ECLOSED.  What was I thinking to ever do anything else?

ctx: Simplify handling for closed contexts.

---

src/core/platform.h
src/platform/posix/posix_atomic.c
src/platform/posix/posix_ipc.h
src/platform/posix/posix_ipcdial.c
src/platform/posix/posix_tcp.h
src/platform/posix/posix_tcpdial.c
src/platform/windows/win_thread.c
src/supplemental/http/http_server.c

performance: reference counters can use relaxed order when incrementing

---

src/sp/transport/ws/websocket.c
src/supplemental/websocket/websocket.c

This covers both the ttransport and the supplemental layers.

websocket: inline the aios

---

src/testing/marry.c
src/testing/nuts.h
src/testing/util.c

We get test failures somewhat frequently due to port conflicts. This attempts to make more of the tests use the trick of binding to port 0, and letting us use the random port instead.

nuts: try to avoid address in use for most tests

---

src/core/device.c

The aio structures need to be finalized, and the sockets should be held until the device is totally finalized to prevent any possible use after free.

device: fixes for socket holds and leaking aio data

---

include/nng/nng.h
src/core/aio.c
src/core/aio.h
src/core/taskq.c
src/core/taskq.h

The use of task_abort to prematurely fail an aio at scheduling time was a mistake, because it could have led to duplicate calls to nng_aio_finish().  We do need to ensure that we leave an indicator so that nni_aio_schedule can return the abort status to caller, in the case that abort is called between the nni_aio_begin and nni_aio_schedule calls.

aio: task_abort was a mistake

---

src/core/dialer.c
src/core/listener.c
src/core/pipe.c
src/core/pipe.h
src/core/socket.c
src/core/sockimpl.h
src/sp/transport.h
src/sp/transport/socket/sockfd.c
src/sp/transport/udp/udp.c

Listener inline

---

src/platform/tcp_stream_test.c
src/platform/windows/win_io.c
src/platform/windows/win_ipcconn.c
src/platform/windows/win_ipclisten.c
src/sp/transport/ipc/ipc_test.c

Windows iopc no close

---

src/core/dialer.c
src/core/listener.c
src/sp/transport.h
src/sp/transport/ipc/ipc.c
src/sp/transport/socket/sockfd.c
src/sp/transport/udp/udp.c

ipc transport: convert to using inline data structures

---

src/core/pipe.c
src/sp/transport/ipc/ipc.c
src/sp/transport/tcp/tcp.c
src/sp/transport/tcp/tcp_test.c

Tcptran aio inline

---

src/core/dialer.c
src/core/listener.c
src/core/pipe.c
src/core/socket.c
src/core/sockimpl.h
src/sp/transport.c
src/sp/transport.h
src/sp/transport/inproc/inproc.c
src/sp/transport/ipc/ipc.c
src/sp/transport/socket/sockfd.c
src/sp/transport/tcp/tcp.c
src/sp/transport/tls/tls.c
src/sp/transport/udp/udp.c
src/sp/transport/ws/websocket.c

Websocket inline

---

src/core/CMakeLists.txt
src/core/log.c

Some POSIX emulations may lack a reasonable syslog function (although syslog is required per the Open Group).  For now we just check for it, and don't use it if it isn't present.

syslog: test for existence

---

.github/workflows/darwin.yml
.github/workflows/linux.yml
.github/workflows/windows.yml
src/platform/posix/posix_pollq.h
src/platform/posix/posix_pollq_poll.c
src/platform/posix/posix_pollq_poll.h
src/platform/posix/posix_udp.c
src/testing/nuts.h

workflows: add pollq and make build debug for backtraces

---

.github/workflows/freebsd.yml
README.md
src/platform/files_test.c
src/platform/posix/CMakeLists.txt
src/platform/posix/posix_resolv_gai.c
src/platform/posix/posix_sockaddr.c
src/platform/posix/posix_tcpdial.c
src/platform/posix/posix_tcplisten.c
src/platform/posix/posix_udp.c
src/platform/udp_test.c

freebsd workflow

---

docs/man/nng_http_req_set_version.3http.adoc
docs/man/nng_http_res_set_version.3http.adoc
include/nng/supplemental/http/http.h
src/supplemental/http/http_msg.c

There are only a few possible reasonable values, and we can intern them to avoid any allocations for it.  (We will probably do the same for the HTTP method shortly as well.)

HTTP: intern the version and avoid allocation

---

demo/rest/server.c
docs/man/nng_http_handler_alloc.3http.adoc
docs/man/nng_http_handler_collect_body.3http.adoc
docs/man/nng_http_handler_set_data.3http.adoc
docs/man/nng_http_handler_set_host.3http.adoc
docs/man/nng_http_handler_set_method.3http.adoc
docs/man/nng_http_handler_set_tree.3http.adoc
docs/man/nng_http_req_set_method.3http.adoc
docs/man/nng_http_res_set_status.3http.adoc
docs/ref/migrate/nng1.md
include/nng/supplemental/http/http.h
src/supplemental/http/http_api.h
src/supplemental/http/http_msg.c
src/supplemental/http/http_public.c
src/supplemental/http/http_server.c
src/supplemental/http/http_server_test.c
src/supplemental/websocket/websocket.c

Httpstatic method

---

src/core/platform.h
src/platform/posix/posix_atomic.c
src/platform/posix/posix_pollq_epoll.c
src/platform/posix/posix_pollq_epoll.h
src/platform/posix/posix_pollq_kqueue.c
src/platform/posix/posix_pollq_kqueue.h
src/platform/posix/posix_pollq_poll.c
src/platform/posix/posix_pollq_poll.h
src/platform/windows/win_thread.c

Atomic bits

---

src/supplemental/websocket/websocket_test.c

These failures are responsible for false SEGFAULTS during testing, as we wind up failing to listen and then proceeding anyway.

websocket test: workaround EADDRINUSE during tests

---

src/sp/transport/socket/sockfd.c
src/sp/transport/tcp/tcp.c
src/sp/transport/tls/tls.c

fix for potential leaking connections

---

include/nng/nng.h
src/core/pipe.c
src/core/socket.c
src/core/sockimpl.h

fixes #961 surprising pipe event order

---

src/platform/posix/posix_resolv_gai.c
src/platform/resolver_test.c
src/platform/windows/win_resolv.c

While here, remove some code paths that do not occur by definition. (For example, if the resolver succeeds, we will definitely have a valid set of addresses, but if it fails, we will definitely not.)

resolver: add some additional test coverage

---

demo/async/CMakeLists.txt
demo/http_client/CMakeLists.txt
demo/pubsub_forwarder/CMakeLists.txt
demo/raw/CMakeLists.txt
demo/reqrep/CMakeLists.txt
demo/rest/CMakeLists.txt
demo/stream/CMakeLists.txt

This fixes problems finding the threads library.  There may still be problems building these with TLS libraries added, as those dependencies may not be satisfied if the library lacks a cmake configuration file.

demos: bump cmake version required to 3.15

---

src/core/aio.c
src/core/aio.h
src/core/aio_test.c
src/platform/posix/CMakeLists.txt
src/platform/posix/posix_ipcconn.c
src/platform/posix/posix_tcpconn.c
src/platform/posix/posix_udp.c
src/platform/udp_test.c
src/sp/transport/udp/udp.c

No recvmsg sendmsg

---

docs/man/nng_tcp_options.5.adoc
docs/ref/tran/ipc.md
include/nng/nng.h
src/platform/ipc_stream_test.c
src/platform/posix/posix_debug.c
src/platform/posix/posix_ipclisten.c
src/platform/posix/posix_tcplisten.c
src/platform/tcp_stream_test.c
src/platform/windows/win_tcplisten.c

This introduces a new option "NNG_OPT_LISTEN_FD", understood by TCP, TLS, and (on POSIX systems) IPC.  This option is used to pass a file descriptor or handle (Windows) that is already listening (ready for ACCEPT to be called).
For TCP and TLS, the socket must be of type AF_INET or AF_INET6, and for IPC it must be of type AF_UNIX.

fixes #863 socket activation: for TCP and IPC (POSIX only)

---

src/platform/ipc_stream_test.c
src/platform/posix/posix_ipc.h
src/platform/posix/posix_ipcdial.c

This involved test-specific hacks, since connect() for UNIX domain sockets always completes synchronously one way or the other, even though it is documented that it might not.  This found a bug, with an uninitialized poll FD as well!

ipc test: add a case for IPC that never connects

---

src/platform/posix/posix_pollq_epoll.c
src/platform/posix/posix_pollq_kqueue.c

Kqueue multiple pollers

---

src/core/socket.c

Pipe reject use after free

---

demo/async/arun.sh
demo/async/client.c

fixes #N/A
Very minor change to enable non-blocking dialing in the client of the async demo (**/demo/async/**).
Client's dial will wait for server to start, and reconnect, but recv and send are still synchronous.
This is a prelude to the development of an async client.

Master drbitboy async demo client part 1

---

src/testing/util.c

This is another occasional test failure due to EADDRINUSE that we can avoid.

tests: use zero port for performance test

---

demo/reqrep/reqrep.c
docs/ref/api/memory.md
docs/ref/api/sock.md
docs/ref/migrate/nanomsg.md
docs/ref/migrate/nng1.md
docs/ref/xref.md
include/nng/nng.h
src/core/sock_test.c
src/nng.c
src/sp/nonblock_test.c

This flag failed to provide real zero copy that it was intended for, and it also involved extra allocations.  Further, the API for it was brittle and error prone.
Modern code should just work directly with nng_msg structures.

api: Remove the NNG_FLAG_ALLOC

---

docs/man/nng_dialer_get.3.adoc
docs/man/nng_listener_get.3.adoc
include/nng/nng.h
src/core/dialer.c
src/core/dialer.h
src/core/listener.c
src/core/listener.h
src/nng.c

Stable ep url sock send recv

---

docs/man/nng_http_conn_read_req.3http.adoc
docs/man/nng_http_conn_write_res.3http.adoc
docs/man/nng_http_handler_alloc.3http.adoc
include/nng/supplemental/http/http.h
src/platform/posix/posix_tcp.h
src/platform/posix/posix_tcpdial.c
src/supplemental/http/http_api.h
src/supplemental/http/http_client.c
src/supplemental/http/http_conn.c
src/supplemental/http/http_msg.c
src/supplemental/http/http_msg.h
src/supplemental/http/http_public.c
src/supplemental/http/http_server.c
src/supplemental/http/http_server_test.c
src/supplemental/websocket/websocket.c
tests/httpclient.c

Http conn req res inline

---

src/supplemental/http/http_server_test.c

http test: test HEAD method in server

---

src/core/url.c
src/core/url.h
src/supplemental/http/http_conn.c
src/supplemental/http/http_msg.c
src/supplemental/http/http_server.c

http: use common canonify at request parse time

---

docs/ref/api/aio.md
docs/ref/api/errors.md
docs/ref/api/http.md
include/nng/http.h
include/nng/nng.h
src/core/aio.c
src/core/aio.h
src/nng.c
src/supplemental/http/http_api.h
src/supplemental/http/http_chunk.c
src/supplemental/http/http_client.c
src/supplemental/http/http_conn.c
src/supplemental/http/http_msg.c
src/supplemental/http/http_public.c
src/supplemental/http/http_server.c
src/testing/marry.c
src/testing/nuts.h
tests/cplusplus_pair.cc

Http nng err

---

src/platform/posix/posix_pollq_epoll.c

posix_pollq_epoll.c:add EPOLLHUP flag to aovid code error continues executing in tcp_cb
the reason of the modification refers to https://github.com/nanomsg/nng/issues/2100

Add EPOLLHUP flag in nni_epoll_thr

---

src/core/aio.c
src/core/aio.h
src/supplemental/http/http_server.c

Fixes #2103 [Warnings with recent compilers clang 19](https://github.com/nanomsg/nng/issues/2103)
(1) First commit just cherry-picks your fix from main.
(2) Provides a simple wrapper for `nni_aio_free()` for use in a reap list to silence UBSAN.
Note these target the stable branch. Do feel free to cherry pick the second commit back to main.
Thanks!

Stable branch: fix for clang 19 compiler warnings

---

src/supplemental/http/http_client.c

This is a bug I found in the past 2 days. Easily reproduce with low number of taskq_threads and set small timeout duration to http connect aio.
basically when aio timeout before the connaio of dialer, and users try to free the http_client obj will end in infinite blocking at `nni_http_client_fini`. Possibly at `nni_aio_free(c->aio);` or `nng_stream_dialer_free(c->dialer);` Both racing case is due to the ingnored aio aborting here. Because the aio_begin is called before it is put into the nni_list. I assume you shall abort it no matter if it is in the dialing list.

* FIX [HTTP] fix a blocking case when freeing http client

---

src/core/aio.c
src/core/aio.h

This just ports #2104 to the main branch for NNG v2.
The commit is identical to [768bcf0](https://github.com/nanomsg/nng/pull/2104/commits/768bcf0a6f6fa065b12b70314e2980a452197e24) (but correctly-formatted for indentation).

Fix for clang 19 compiler warnings (main branch)

---

src/supplemental/tls/mbedtls/mbedtls.c
src/supplemental/tls/tls_test.c

An explicit call to `mbedtls_ssl_set_hostname(NULL)` is now required if the hostname should not be verified in handshake. From the mbedtls changelog:
```
= Mbed TLS 3.6.3 branch released 2025-03-24
Default behavior changes
* In TLS clients, if mbedtls_ssl_set_hostname() has not been called,
mbedtls_ssl_handshake() now fails with MBEDTLS_ERR_SSL_CERTIFICATE_VERIFICATION_WITHOUT_HOSTNAME if certificate-based authentication of the server is attempted.
This is because authenticating a server without knowing what name
to expect is usually insecure. To restore the old behavior, either
call mbedtls_ssl_set_hostname() with NULL as the hostname, or
enable the new compile-time option MBEDTLS_SSL_CLI_ALLOW_WEAK_CERTIFICATE_VERIFICATION_WITHOUT_HOSTNAME.
```

fixes mbedtls 3.6.3 handshake with NULL server name
