nanomsg/nng

src/core/socket.c, src/nng.c, src/nng.h, src/platform/posix/posix_pollq_poll.c, src/platform/windows/win_thread.c, src/protocol/pair/pair_v1.c, tests/CMakeLists.txt, tests/device.c, tests/message.c, tests/pair1.c, tests/sock.c
This includes new methods and test for 32-bit message accesses, a fix for posix pollq's not being idempotent on finalizers, and rich testing for the pairv1 protocol.
=> pairv1 polyamorous mode + fixes

src/core/endpt.c, src/core/idhash.c, src/core/idhash.h, src/core/pipe.c, src/core/socket.c, tests/idhash.c
We want this for zerotier, where conversation Ids will be 64-bits.
=> Support 64-bit IDs.

src/core/aio.c, src/core/aio.h, src/platform/posix/posix_pollq_poll.c, src/platform/posix/posix_sockaddr.c, src/platform/posix/posix_udp.c, src/platform/windows/win_debug.c, src/platform/windows/win_impl.h, src/platform/windows/win_iocp.c, src/platform/windows/win_sockaddr.c, tests/tcp.c, tests/udp.c
The purpose of this is to increase the test coverage of the UDP code.
=> Improve UDP test coverage.

src/CMakeLists.txt, src/core/platform.h, src/platform/posix/posix_file.c, src/platform/windows/win_debug.c, src/platform/windows/win_file.c, src/transport/zerotier/zerotier.c, tests/CMakeLists.txt, tests/files.c, tests/zt.c
This moves storage functionality into the platform code, and adds directory traversal & management, APIs to determine common directories (homedir, tempdir), and a test suite.
=> Storageapi

docs/nng_tls.adoc, docs/nng_ws.adoc, src/core/aio.c, src/core/aio.h, src/core/endpt.c, src/nng.h, src/supplemental/tls/mbedtls/tls.c, src/transport/inproc/inproc.c, src/transport/tls/tls.c, src/transport/ws/websocket.c, src/transport/ws/websocket.h, tests/tls.c, tests/wssfile.c
fixes #210 Want NNG_OPT_TLS_* options for TLS transport
fixes #212 Eliminate a_endpt member of aio
=> fixes #209 NNG_OPT_TLS_VERIFIED is busted

CMakeLists.txt, src/core/aio.c, src/core/aio.h, src/nng.c, src/nng.h, src/platform/posix/posix_pipedesc.c, src/platform/posix/posix_udp.c, src/platform/windows/win_ipc.c, src/platform/windows/win_tcp.c, src/platform/windows/win_udp.c, src/supplemental/http/http_conn.c, src/supplemental/tls/mbedtls/tls.c, tests/aio.c
I've tested this on macOS -- Windows tests are needed (by CI).
=> fixes #228 aio iov should have larger limits (dynamically allocated)

docs/man/nngcat.adoc, src/core/msgqueue.c, src/supplemental/tls/CMakeLists.txt, src/supplemental/tls/mbedtls/tls.c, src/supplemental/tls/none/tls.c, tools/nngcat/nngcat.c
While here we also fixed a bug in the --file handling that we noticed
while writing the TLS handling.
=> fixes #247 nngcat needs TLS options

src/platform/posix/posix_pollq_kqueue.c
=> kqueue: add license info

src/core/file.c, src/core/file.h, src/core/platform.h, src/platform/posix/posix_file.c, src/platform/posix/posix_impl.h, src/platform/windows/win_debug.c, src/platform/windows/win_file.c, src/platform/windows/win_impl.h, src/platform/windows/win_tcp.c, src/supplemental/tls/none/tls.c, src/transport/zerotier/zerotier.c, tests/pollfd.c, tools/nngcat/nngcat.c
fixes #267 zerotier transport should lock ZT_HOME
=> fixes #265 nngcat should support persistent ZT nodes

_adoc/RATIONALE.adoc
=> Add a missing ` in the doc

src/core/aio.c, src/platform/posix/posix_pollq_epoll.c, src/supplemental/websocket/websocket.c
This also gives a performance benefit to WebSocket, by making
the completion logic run synchronously.
=> fixes #315 WebSocket message handling errors

src/core/endpt.c, src/core/options.c, src/core/options.h, src/core/protocol.h, src/core/socket.c, src/core/transport.c, src/core/transport.h, src/protocol/bus0/bus.c, src/protocol/pair0/pair.c, src/protocol/pair1/pair.c, src/protocol/pipeline0/pull.c, src/protocol/pipeline0/push.c, src/protocol/pubsub0/pub.c, src/protocol/pubsub0/sub.c, src/protocol/reqrep0/rep.c, src/protocol/reqrep0/req.c, src/protocol/survey0/respond.c, src/protocol/survey0/survey.c, src/transport/ipc/ipc.c, src/transport/tcp/tcp.c, src/transport/tls/tls.c, src/transport/ws/websocket.c, src/transport/zerotier/zerotier.c, tests/sock.c
This adds support for validating option types when setting.  The sock test needed to be fixed too.
=> fixes #329 type checking not done for setopt

docs/man/nn_getsockopt.3compat.adoc, docs/man/nn_poll.3compat.adoc, docs/man/nng_compat.3compat.adoc, src/compat/nanomsg/nn.c, src/core/msgqueue.c, src/core/msgqueue.h, src/core/pollable.c, src/core/socket.c, tests/CMakeLists.txt, tests/compat_poll.c, tests/compat_testutil.h
This includes the test from legacy libnanomsg and a man page.
=> fixes #344 nn_poll() legacy API missing

src/protocol/reqrep0/rep.c
While here I've added some code that should help us backtrack on
a crash, by linking back to the pipe from the context when we
are queued on that pipes sendq.
I'm not sure if we've ever seen these or not, but it could explain
certain infrequent crashes we think we've seen.
=> fixes #355 Possible use after free in REP

src/core/aio.c, src/core/aio.h, src/core/device.c, src/core/endpt.c, src/core/msgqueue.c, src/core/msgqueue.h, src/platform/posix/posix_epdesc.c, src/platform/posix/posix_pipedesc.c, src/platform/posix/posix_resolv_gai.c, src/platform/posix/posix_udp.c, src/platform/windows/win_iocp.c, src/platform/windows/win_ipc.c, src/platform/windows/win_resolv.c, src/protocol/reqrep0/rep.c, src/protocol/reqrep0/req.c, src/supplemental/http/http_client.c, src/supplemental/http/http_conn.c, src/supplemental/http/http_public.c, src/supplemental/http/http_server.c, src/supplemental/tls/mbedtls/tls.c, src/supplemental/websocket/websocket.c, src/transport/inproc/inproc.c, src/transport/ipc/ipc.c, src/transport/tcp/tcp.c, src/transport/tls/tls.c, src/transport/ws/websocket.c, src/transport/zerotier/zerotier.c
This is work being done for #346 but this is very much a work in progress.
I suspect and hope that this refactoring will address the main issue.  Note that the work to support this is going to have a deleterious impact on performance as it increases the pressure on the nni_aio_lk, but future work will be done to mitigate that.  Right now we have to make this *correct*, we'll optimize it later.
=> Nonblocking -refactoring -- work in progress, not for merging

docs/man/nng_respondent.7.adoc, src/core/msgqueue.c, src/core/msgqueue.h, src/core/socket.c, src/nng.c, src/nng.h, src/protocol/reqrep0/rep.c, src/protocol/reqrep0/xrep.c, src/protocol/reqrep0/xreq.c, src/protocol/survey0/CMakeLists.txt, src/protocol/survey0/respond.c, src/protocol/survey0/survey.c, src/protocol/survey0/xrespond.c, src/protocol/survey0/xsurvey.c, tests/CMakeLists.txt, tests/compat_surveyttl.c, tests/reqpoll.c, tests/respondpoll.c, tests/stubs.h, tests/survey.c, tests/surveyctx.c, tests/surveypoll.c
This is untested context support for Surveyor.  (Both sides).  Do not integrate yet.
=> This provides a basic implementation for Surveyor & Respondent contexts

src/core/msgqueue.c, src/core/msgqueue.h
=> fixes #364 kill off nni_msgq_set_best_effort()

docs/man/libnng.3.adoc, docs/man/nng_ctx.5.adoc, docs/man/nng_ctx_id.3.adoc, docs/man/nng_dialer.5.adoc, docs/man/nng_dialer_id.3.adoc, docs/man/nng_listener.5.adoc, docs/man/nng_listener_id.3.adoc, docs/man/nng_pipe.5.adoc, docs/man/nng_pipe_close.3.adoc, docs/man/nng_pipe_id.3.adoc, docs/man/nng_socket.5.adoc, docs/man/nng_socket_id.3.adoc, src/core/pipe.c, src/nng.c, src/nng.h, tests/message.c, tests/pair1.c, tests/reconnect.c, tests/sock.c, tests/surveyctx.c, tests/tcp.c, tests/tcp6.c, tests/tls.c, tests/trantest.h, tests/ws.c, tests/wss.c, tests/wssfile.c, tests/zt.c
=> fixes #381 Want comparators for various types

src/core/transport.c
Doesn't fix any reported issue.
=> Do not include files you won't need

src/protocol/reqrep0/rep.c, tests/multistress.c, tests/reqstress.c
=> fixes #424 reqstress low frequency crash

src/platform/posix/posix_resolv_gai.c, src/platform/windows/win_resolv.c, src/platform/windows/win_tcp.c, tests/ipcwinsec.c, tests/resolv.c
fixes #438 Consider dropping AI_V4MAPPED
=> fixes #430 Unable to build in MSYS + Win-builds

.circleci/config.yml, src/core/panic.c, tests/httpserver.c
=> Attempt to switch to clang 6 on xenial.

docs/man/nng_bus.7.adoc, src/protocol/bus0/bus.c
=> fixes #441 Unintentional semantic in bus protocol

docs/man/nng_tcp.7.adoc, docs/man/nng_tls.7.adoc, src/transport/tcp/tcp.c, src/transport/tls/tls.c
=> fixes #452 Want tcp6:// and tcp4:// to constrain IP family

src/core/msgqueue.c, src/protocol/pubsub0/sub.c
As part of this code fix, we needed to add filtering support to the
msgq_tryput code path -- it turns out that code path was bypassing
the filterfn altogether.
Eventually we'll remove all this filtering stuff from the msgq code
and replace it with inline filtering directly in sub.
=> fixes #459 SUB should be more aggressive about discarding messages

README.adoc, README.html, docs/BUILD_ANDROID.adoc, docs/BUILD_CROSSCOMPILE.adoc, docs/BUILD_IOS.adoc, docs/BUILD_TLS.adoc, docs/BUILD_ZEROTIER.adoc
This contains a number of changes to the documentation, positioning it for release.
Feedback from community members is sincerely desired.
=> Readme and doc updates for release

src/core/aio.c
=> fixes #535 aio->a_closed and aio->a_stop could be consolidated

src/supplemental/websocket/websocket.c, src/transport/ws/websocket.c
I've been running a compat_ws for some time now.  Before this change it failed about one time in 10.  (Maybe even less often.)  After over 1000 runs of the test, over the course of over an hour, it seems solid now.
=> fixes #518 Panic in compat_ws -- use after free?

src/supplemental/websocket/websocket.c
=> fixes #545 uaio assertion error in ws

src/platform/posix/posix_epdesc.c
=> fixes #576 IPC listen unlinks UNIX socket on failure

src/core/aio.c
=> fixes #625 aio->a_stop/aio_begin may be too severe

src/protocol/reqrep0/req.c
This adds a proper boolean condition for the pipe being closed
(removing the unused sending flag), and adds checks for both the
pipe closed and the socket closed flags at key points.
=> fixes #628 Hang in closing REQ

src/transport/ipc/ipc.c
=> fixes #630 IPC start elimination

src/transport/ipc/ipc.c
=> fixes #640 IPC leaks found

src/transport/ipc/ipc.c
=> fixes #615 IPC close on Windows leaves handle open

src/supplemental/http/http_client.c
=> fixes #639 Memory leak in http client

src/transport/ipc/ipc.c, src/transport/tcp/tcp.c, src/transport/tls/tls.c, tests/tls.c
=> fixes #644 remove start from TLS code

src/transport/zerotier/zerotier.c
=> fixes #645 remove start from ZeroTier transport

src/core/dialer.c, src/core/sockimpl.h, src/platform/posix/posix_ipclisten.c
=> fixes #654 use aio for synchronous connect

src/supplemental/websocket/websocket.c
fixes #651 Use after free in websocket
=> fixes #638 Race condition detected in websocket

src/core/dialer.c, src/core/socket.c
This is a fairly painful bug if you hit it.
=> fixes #693 Failed dial results in hard spin

src/transport/zerotier/zerotier.c
=> fixes #755 zerotier transport segfaults on alpine linux

src/supplemental/util/options.c
=> fixes #763 buffer overrun in options test

src/core/options.c, tests/sock.c
Reported by @TBastiani (with suggested fix).  Test validation added.
=> fixes #766 NNG asserts when setting socket name

docs/man/CMakeLists.txt, docs/man/nng_http_client_get_tls.3http.adoc, docs/man/nng_http_handler_alloc.3http.adoc, docs/man/nng_http_server_get_tls.3http.adoc, docs/man/nng_tls.7.adoc, docs/man/nng_tls_config_alloc.3tls.adoc, docs/man/nng_tls_config_hold.3tls.adoc, docs/man/nng_ws.7.adoc, src/supplemental/http/http_client.c, src/supplemental/http/http_server.c, src/supplemental/tls/CMakeLists.txt, src/supplemental/tls/mbedtls/tls.c, src/supplemental/tls/tls.h, src/transport/tls/tls.c, src/transport/ws/websocket.c
fixes #776 Configuration of mbedTLS should warn about license
=> fixes #456 TLS configuration object hold

src/core/pipe.c, src/core/socket.c, src/core/sockimpl.h, src/core/stats.c, src/core/stats.h
=> fixes #782 stat namespace collision on QNX

tests/CMakeLists.txt, tests/convey.c
=> fixes #784 convey uses langinfo not available on QNX

src/nng.h
Fixes #791  Incorrect minor and patch versions
=> Update the minor and patch versions

tools/nngcat/nngcat.c
=> added option --msgpack to static nng_optspec opts to match documentation

src/core/msgqueue.c, src/core/msgqueue.h
=> fixes #812 message queue put_error unused

include/nng/supplemental/ipc/ipc.h, src/core/defs.h, src/core/dialer.c, src/core/dialer.h, src/core/listener.c, src/core/listener.h, src/core/options.c, src/core/options.h, src/core/pipe.c, src/core/platform.h, src/core/socket.c, src/core/transport.c, src/core/transport.h, src/nng.c, src/platform/posix/posix_ipc.h, src/platform/posix/posix_ipcconn.c, src/platform/posix/posix_ipcdial.c, src/platform/posix/posix_ipclisten.c, src/platform/windows/win_ipc.h, src/platform/windows/win_ipcconn.c, src/platform/windows/win_ipcdial.c, src/platform/windows/win_ipclisten.c, src/supplemental/ipc/CMakeLists.txt, src/supplemental/ipc/ipc.c, src/transport/inproc/inproc.c, src/transport/ipc/ipc.c, tests/ipc.c, tests/ipcsupp.c
This completes the option handling for IPC and inproc, as well as framework support for said options.
=> inproc and IPC options (834 and 835)

src/protocol/reqrep0/rep.c, src/protocol/survey0/respond.c
=> fixes #871 panic when sharing rep between threads

src/supplemental/websocket/websocket.c, tests/CMakeLists.txt, tests/wsstream.c
This also includes a test suite for the websocket stream mode and wild card binding.
=> fixes #882 websocket stream mode doesn't copy received data

src/transport/zerotier/zerotier.c
nni_getopt needs extra var (recent changes)
=> fix zt_pipe_getopt

src/transport/zerotier/zerotier.c
There is quite some package loss, which I will pursue
later (in nng / zerotier). For now it helps to tune these settings
to keep the peer relations.
=> Tuning zt transport ping

docs/man/CMakeLists.txt, docs/man/libnng.3.adoc, docs/man/nng_ctx_get.3.adoc, docs/man/nng_ctx_getopt.3.adoc, docs/man/nng_ctx_set.3.adoc, docs/man/nng_ctx_setopt.3.adoc, docs/man/nng_dialer_get.3.adoc, docs/man/nng_dialer_getopt.3.adoc, docs/man/nng_dialer_set.3.adoc, docs/man/nng_dialer_setopt.3.adoc, docs/man/nng_getopt.3.adoc, docs/man/nng_listener_get.3.adoc, docs/man/nng_listener_set.3.adoc, docs/man/nng_listener_setopt.3.adoc, docs/man/nng_pipe_get.3.adoc, docs/man/nng_socket_get.3.adoc, docs/man/nng_socket_set.3.adoc, include/nng/nng.h, src/core/options.h, src/core/stream.c, src/nng.c, src/platform/windows/win_pipe.c
fixes #901 Stream get/set functions should be getopt/setopt
Just a global search and replace.  Renamed adoc files as well.
=> fixes #901 get/set function naming consistency

src/supplemental/http/http_client.c
Otherwise connections are not closed in reaper.
=> set txn->client in nni_http_transact

src/supplemental/http/http_chunk.c
=> Fix for http chunked transfer

CMakeLists.txt
=> fixes #956 pthread_atfork error on Arm processor

src/transport/zerotier/zerotier.c
This should be a better solution than #974 --  testing still needed.
=> fixes #979 ZeroTier fails with zero recvmax

perf/perf.c
Types passed to printf must match.
=> Complaints found by automated CI.

.github/workflows/darwin.yml, .github/workflows/linux.yml, .github/workflows/windows.yml
=> Initial swag at GitHub actions.

README.adoc
=> New badge styles, badges for lgtm and workflows.

CMakeLists.txt, src/platform/posix/posix_config.h, tests/testutil.c
=> fixes #1038 Linux should use getentropy or getrandom

src/platform/posix/posix_ipc.h, src/platform/posix/posix_ipcconn.c, src/platform/posix/posix_ipcdial.c, src/platform/posix/posix_tcp.h, src/platform/posix/posix_tcpconn.c, src/platform/posix/posix_tcpdial.c
A similar change will be needed for IPC.  Need to investigate
IPC, and also TCP listeners and Windows.
=> Reference count TCP dialers. (WIP)

tests/httpclient.c
=> fixes #940 httpclient Timeout can succeed in cloud

src/core/platform.h, src/platform/posix/posix_resolv_gai.c, src/platform/windows/win_resolv.c
This just yanks some dead code (thanks to codecov for identifying it.)
=> fixes #1051 nni_ntop is unused

.codecov.yml, .github/workflows/coverage.yml, .github/workflows/darwin.yml, .github/workflows/linux.yml
=> Fix codecov ignore paths.

tests/aio.c, tests/testutil.h
=> fixes #1042 testutil.h could offer better test failure diagnosis

.github/workflows/sanitizer.yml, src/core/dialer.c, src/core/list.h, src/core/listener.c, src/core/pipe.c, src/core/socket.c, src/core/stats.c, src/core/stats.h, src/protocol/pair1/pair.c, src/supplemental/websocket/websocket.h, src/supplemental/websocket/wssfile_test.c
fixes #1063 Include sanitizer runs in CI
fixes #1068 Wssfile test sometimes fails with wrong error code
While here, addressed a number of clang-tidy items, and some light
cleanup of code we were already in.
=> fixes #1064 Potential deadlock in statistics code

src/core/platform.h, src/platform/posix/posix_atomic.c, src/platform/posix/posix_impl.h, src/platform/posix/posix_resolv_gai.c, src/platform/windows/win_impl.h, src/platform/windows/win_resolv.c, src/platform/windows/win_thread.c, src/supplemental/http/http_server.c, src/supplemental/tcp/tcp.c
This also introduces a new atomic boolean type, so we can use that
to trigger whether we've added the HTTP handler or not.
=> fixes #1075 WebSocket heap use after free

src/nng.c
Adds error message for error NNG_ECONNSHUT.
=> Add error message for NNG_ECONNSHUT

src/protocol/reqrep0/CMakeLists.txt, src/protocol/reqrep0/rep.c, src/protocol/reqrep0/rep_test.c, tests/testutil.h
We've also added some TEST_NNG_SEND_STR and TEST_NNG_RECV_STR to
help with convenience when writing test code.
=> fixes #1088 REP protocol does not signal SENDFD properly

CMakeLists.txt, src/core/strs.c, src/core/strs.h
=> fixes #1090 nni_strlcat is unused

.github/workflows/darwin.yml, .github/workflows/linux.yml, .github/workflows/sanitizer.yml, .github/workflows/windows.yml
=> GitHub actions need to run on pull requests too.

src/protocol/reqrep0/rep_test.c
=> More REP protocol coverage tests.

src/core/defs.h, src/core/pipe.c, src/core/protocol.h, src/core/socket.c, src/core/sockimpl.h, src/protocol/bus0/bus.c, src/protocol/pair0/pair.c, src/protocol/pair1/pair.c, src/protocol/pipeline0/pull.c, src/protocol/pipeline0/push.c, src/protocol/pubsub0/pub.c, src/protocol/pubsub0/sub.c, src/protocol/pubsub0/xsub.c, src/protocol/reqrep0/rep.c, src/protocol/reqrep0/req.c, src/protocol/reqrep0/xrep.c, src/protocol/reqrep0/xreq.c, src/protocol/survey0/respond.c, src/protocol/survey0/survey.c, src/protocol/survey0/xrespond.c, src/protocol/survey0/xsurvey.c
fixes #1103 respondent could inline backtrace
=> fixes #1104 move allocation of protocol objects to common core

docs/man/nng_aio_set_iov.3.adoc, src/core/aio.c, src/core/aio.h, tests/platform.c
fixes #1097 aio prov_data not used at all
=> fixes #1096 inline all 16 iovs in aio (also consider reducing -- to 8?)

src/core/taskq.c
=> no more task_reap.

src/core/aio.c, src/core/taskq.c, src/core/taskq.h
=> fixes #1117 task structures should be inlined

src/protocol/reqrep0/CMakeLists.txt, src/protocol/reqrep0/xrep.c, src/protocol/reqrep0/xrep_test.c
=> fixes #1124 data race on ttl in xrep

src/protocol/survey0/CMakeLists.txt, src/protocol/survey0/xsurvey.c, src/protocol/survey0/xsurvey_test.c
=> XSURVEY test suite added.

src/nng.c, src/protocol/survey0/CMakeLists.txt, src/protocol/survey0/respond.c, src/protocol/survey0/respond_test.c
Also, add a test to cover the RESPOND protocol.  This gets about
95% of the coverage.
=> RESPOND needs to use atomic for TTL.

include/nng/protocol/pair1/pair.h, src/protocol/pair1/pair.c, src/protocol/pair1/pair1_test.c
We've also finished fleshing out the statistics for pairv1, addressed a
possible race around the TTL, and added additional test cases to validate
things.  We also have tightened up the send logic to ensure we do not
send a bad message on the wire (drop the malformed message on the send side).
=> fixes #1151 minor pairv1 optimizations possible

src/transport/inproc/inproc.c
In addition, the message queue code is rather heavy weight, so this may
make the inproc code a bit leaner.  It also makes backpressure conditions
much more reliable since it now is completely unbuffered.
=> fixes #1159 inproc could skip message queue

src/protocol/reqrep0/req_test.c
This actually uncovered a subtle problem with retry, where we could
wind up rescheduling the retry on the wrong pipe.  We are intended to
have tries be "sticky" (as long as the pipe that services the request
originally is still available.)
A subtle note though: when devices are involved, the request won't
necessarily be directed the same way, as the device doesn't have the
state to remember that.
=> fixes #1162 req_test needs to have better retry tests

src/platform/posix/posix_atomic.c, src/platform/posix/posix_impl.h
=> fixes #1182 v1.2.5 build fails gcc 4.8

src/protocol/pair0/pair.c
=> inline the pipe aios for pair0

src/protocol/survey0/survey.c
=> Survey occasionally does not cancel properly.

demo/rest/server.c, include/nng/compat/nanomsg/ipc.h, include/nng/compat/nanomsg/nn.h, include/nng/nng.h, include/nng/supplemental/util/platform.h, src/core/aio.c, src/supplemental/http/http_server.c, src/transport/zerotier/zerotier.c
Cleanup some typos in the comments.
=> Fix typos in comments

include/nng/supplemental/http/http.h
=> Update comments in http.h

src/nng.c, tests/sock.c
This adds both a test case, and a fix.
=> fixes #1201 Unexpected error return code: NNG_ENOMEM

src/core/message.c, src/core/message.h, src/nng.c, src/protocol/bus0/bus.c, src/protocol/pair1/pair.c, src/protocol/pair1/pair1_poly.c, src/protocol/reqrep0/req.c, src/protocol/reqrep0/xrep.c, src/protocol/survey0/survey.c, src/protocol/survey0/xrespond.c
=> Inlineheader

src/transport/zerotier/zerotier.c
=> Fix type and object access when adding local interfaces.

tests/message.c
=> Fix message realloc test off by one str comparison

src/core/aio.c, src/core/taskq.c, src/core/taskq.h, src/transport/tcp/tcp.c
I'm not sure if this actually closes issue or not.  It may also have other problems.  I'd like folks to help me test it out, ideally.
=> fixes #1236 Deadlock triggered on nng_close

src/supplemental/tls/tls_common.c, src/supplemental/tls/tls_test.c, tests/testutil.c, tests/testutil.h
This also starts the test framework NNG streams, so that we can
test those more directly.
=> Tests for sending large amounts of data over NNG TLS streams.

src/core/defs.h, src/core/dialer.c, src/core/listener.c, src/transport/inproc/inproc.c, src/transport/ipc/ipc.c, src/transport/tcp/tcp.c, src/transport/tls/tls.c
Also, addressed a number of Clang-tidy complaints. Potential hangs
in close addressed as well.
=> fixes #1239 Use after free in tls

src/platform/posix/posix_ipcconn.c
=> Fix build on FreeBSD

docs/man/nng_ws.7.adoc, src/core/stream.c, src/supplemental/http/http_server.c, src/transport/ws/websocket.c, tests/tcp.c, tests/udp.c, tests/ws.c
fixes #1277 FreeBSD errors due to bad v4 vs. v6 assumptions
=> fixes #1279 Add support for ws4:// and ws6:// style websocket urls

CMakeLists.txt, docs/man/CMakeLists.txt, docs/man/libnng.3.adoc, docs/man/nng_thread_set_name.3supp.adoc, include/nng/nng.h, include/nng/supplemental/util/platform.h, src/core/aio.c, src/core/platform.h, src/core/reap.c, src/core/taskq.c, src/core/thread.c, src/core/thread.h, src/core/timer.c, src/platform/posix/posix_pollq_epoll.c, src/platform/posix/posix_pollq_kqueue.c, src/platform/posix/posix_pollq_poll.c, src/platform/posix/posix_pollq_port.c, src/platform/posix/posix_resolv_gai.c, src/platform/posix/posix_thread.c, src/platform/windows/win_io.c, src/platform/windows/win_ipcdial.c, src/platform/windows/win_resolv.c, src/platform/windows/win_thread.c, src/supplemental/util/platform.c, src/transport/zerotier/zerotier.c
=> Threadname

src/protocol/pubsub0/sub.c
=> fixes #1308 Sub contexts/AIOs can share a single nng_msg

docs/man/nng_sockaddr_in6.5.adoc, include/nng/nng.h, src/platform/posix/posix_resolv_gai.c, src/platform/posix/posix_sockaddr.c, src/platform/windows/win_resolv.c, src/platform/windows/win_sockaddr.c
This is a test draft -- not really tested yet, since I don't have much in the way of systems to test with.  I'm just passing through the values provided by getaddrinfo().
Testing help is requested.
=> fixes #1022 Support tcp6 link local addresses

src/protocol/reqrep0/req.c, src/protocol/reqrep0/req_test.c
=> fixes #1300 REQ should fast fail if retry timer is zero (on disconnect)

src/core/aio.c, src/core/aio.h, src/core/platform.h, src/platform/posix/posix_resolv_gai.c, src/platform/posix/posix_tcpdial.c, src/platform/windows/win_resolv.c, src/platform/windows/win_tcpdial.c, src/supplemental/tcp/tcp.c, src/transport/tcp/tcp.c, src/transport/tls/tls.c, tests/CMakeLists.txt, tests/resolv.c
fixes #1317 IPv6 listener get port is incorrect
=> Remove sockaddr from aio.

src/core/stats.c, src/core/stats.h
=> fixes #1329 stats could lose parent and private fields

man/tip/_toc.html, man/tip/index.html, man/tip/libnng.3.html, man/tip/nng_ipc.7.html, man/tip/nng_sockaddr.5.html, man/tip/nng_sockaddr_abstract.5.html, man/tip/nng_sockaddr_in6.5.html, man/tip/nng_sockaddr_ipc.5.html, man/tip/nng_thread_set_name.3supp.html, man/tip/nng_ws.7.html
=> Manual page updates for tip

src/core/pipe.c, src/core/socket.c, src/core/stats.c
Add missing #define sentences and minor correct for macro.
=>  *Fix Add missing #define when disabling NNG_ENABLE_STATS

src/transport/ipc/ipc_test.c, tests/ipc.c, tests/set_recvmaxsize.c
=> fixes #1351 Move IPC dialer and listener props tests into new test suite

src/supplemental/http/CMakeLists.txt, src/supplemental/http/http_api.h, src/supplemental/http/http_client.c, src/supplemental/http/http_schemes.c, src/supplemental/http/http_server.c, src/supplemental/websocket/CMakeLists.txt, src/supplemental/websocket/wssfile_test.c
This also properly reenables the wssfile_test.
=> fixes #1355 wss4 and wss6 don't work as they should

src/nng.c
=> fixes #1365 nng_recvmsg returns NNG_ETIMEDOUT rather than NNG_EAGAIN

src/protocol/pubsub0/sub.c
This hopefully addresses the problem of both missed poll
events (meaning we don't flag the descriptor as pollable),
and spurious poll events (which might have happened when a
message was delivered synchronously.)
[TESTING PENDING]
=> fixes #1368 Incorrect recv pollfd handing for SUB.

src/core/aio.c
fixes #1048 nng_aio reuse error messages are unhelpful
=> fixes #1380 nni_aio optimizations

src/compat/nanomsg/nn.c
Fix possible compilation error.
=> Fix compilation error

src/platform/posix/posix_thread.c
=> fixes #1363 build ios version fails

src/protocol/pair1/pair.c
=> fixes #1389 PAIRv1 can remove a few bits

CMakeLists.txt, src/compat/nanomsg/nn.c, src/tools/nngcat/nngcat.c, src/tools/perf/pubdrop.c
=> Fix compilation errors when NNG_ELIDE_DEPRECATED is ON

src/core/dialer.c, src/core/listener.c, src/supplemental/http/http_public.c
=> Fix compilation warnings

src/core/message.c, src/core/message.h, src/core/reconnect_test.c, src/sp/protocol/pair1/pair.c, src/sp/protocol/pair1/pair1_test.c
This is only the pair v1 protocol.  Pair v0 and polyamorous mode
still have work to do.  We probably won't "fix" the performance for
poly mode since that's deprecated anyway.
=> fixes #808  Very slow PAIR performance compared to nanomsg

src/core/protocol.h
This fixes a "bug" introduced in 840f968d.
=> Fix comment in protocol.h

src/core/thread.c, src/sp/transport/ws/ws_test.c
=> fixes #1413 nni_thr_setname NULL pointer dereference

src/sp/protocol/pair1/pair.c, src/testing/marry.c
=> fixes #1415 pair.c compiler warning

src/sp/protocol/pair0/CMakeLists.txt, src/sp/protocol/pair0/pair.c, src/sp/protocol/pair0/pair0_test.c
This takes the performance work we did for pairv1, and provides an
implementation for pairv0.  The upshot should be a nice performance
boost for pair v0.
=> fixes #1419 pairv0 performance work

src/sp/transport/tcp/tcp.c, src/sp/transport/tcp/tcp_test.c, src/sp/transport/tls/tls.c
=> fixes #1421 Failure in tcp and tls local source handling

demo/reqrep/CMakeLists.txt, demo/reqrep/reqrep.c
Extend the ReqRep demo with the ZeroTier transport.
=> Extend the reqdep demo with ZeroTier transport

src/core/aio_test.c, src/core/socket.c
=> fixes #1456 bad access in OSX thread on nn

src/platform/posix/posix_ipclisten.c
This backs out the changes for #1326, because fchmod on sockets
doesn't actually work on Linux, even though it returns success.
=> fixes #1465 NNG_OPT_IPC_PERMISSIONS stopped working

src/core/aio.c
=> Fix the wrong ratio when expire queue shrink.

src/core/aio.c
fixes #1486
Be aware this is just a prefix to make it functional.
=>  * FIX #1486 by waking up latest aio each time.

src/platform/windows/win_ipclisten.c
=> fixes #1347 windows IPC accept cancellation not wired up

demo/async/CMakeLists.txt, demo/http_client/CMakeLists.txt, demo/raw/CMakeLists.txt, demo/reqrep/CMakeLists.txt, demo/reqrep/reqrep.c, demo/rest/CMakeLists.txt
Update the demos to not use deprecated functions
=> update demos to not use deprecated functions

.clang-format, src/core/socket.c, src/nng.c
(Note that this includes some incorrect formatting due to an apparent
bug in clang-format 13.  Hopefully they'll fix it later, but for now
I'm preserving the bad whitespace.)
=> Fix incorrect elides of deprecated code.

src/core/dialer.c, src/core/dialer.h, src/core/idhash.c, src/core/idhash.h, src/core/init.c, src/core/listener.c, src/core/listener.h, src/core/pipe.c, src/core/pipe.h, src/core/socket.c, src/core/socket.h, src/core/stats.c, src/core/stats.h, src/sp/transport/inproc/inproc.c
This also arranges to clean up the maps at nng_fini time.
=> ID map static initialization support.

demo/rest/README.adoc
=> Fixed a command error

src/core/aio.c, src/core/dialer.c, src/sp/transport/ipc/ipc.c, src/sp/transport/tcp/tcp.c
=> Don't bump error counters for NNG_ECLOSED.

src/core/socket.c
We try to move the msgq close up earler.  While here we can stop dropping and reacquiring the lock -- this is likely left over and may lead to races.
=> Socket close may leak messages.

src/core/pipe.c, src/core/socket.c
=> fixes #1610 nni_sock_open() in socket.c: use after free

src/supplemental/http/http_server.c
=> fixes#1611 http_sconn_error() in http_server.c; use after free

CMakeLists.txt, src/core/aio.c, src/core/listener.c, src/core/socket.c, src/core/sockimpl.h
=> fixes #1619 Expose NNG_MAX_EXPIRE_THREADS via CMake

src/core/dialer.c, src/core/socket.c, src/core/sockimpl.h
=> fixes #1658 Possible use-after-free in dialer

docs/man/nng_http_handler_collect_body.3http.adoc
=> [fixed] fix description of function nng_http_handler_collect_body()

src/sp/protocol/reqrep0/req.c, src/sp/protocol/reqrep0/req_test.c
=> fixes #1702 segfault canceling req receive while sending

src/compat/nanomsg/CMakeLists.txt, src/compat/nanomsg/compat_msg_test.c, src/compat/nanomsg/nn.c
=> fixes #1701 compat: nn_reallocmsg is incorrect

src/core/platform.h, src/platform/posix/posix_socketpair.c, src/platform/windows/win_socketpair.c, src/supplemental/util/platform.c
=> Fix warning from inconsistent socket_pair prototype.

docs/man/CMakeLists.txt, docs/man/libnng.3.adoc, docs/man/nng_log.3.adoc, docs/man/nng_log_set_facility.3.adoc, docs/man/nng_log_set_level.adoc, docs/man/nng_log_set_logger.adoc, include/nng/nng.h, src/core/CMakeLists.txt, src/core/log.c, src/core/log_test.c
Includes test code.  Docs coming soon.
=> fixes #543 Add logging support framework

src/supplemental/tls/tls_common.c
This was discussed with jaylin.
=> [tls_common] finish conn lock in tls_reap

cmake/NNGOptions.cmake
=> Missed config option for UDP

src/platform/windows/win_ipclisten.c, src/platform/windows/win_tcpconn.c
Cherry picks these commits to the stable branch.
=> Silence compiler warnings for Windows

src/core/url.c
=> fix parsing bug in abstract URLs

docs/man/nng_dialer_set.3.adoc, docs/man/nng_ipc_options.5.adoc, docs/man/nng_listener_set.3.adoc, docs/man/nng_stream_dialer_set.3str.adoc, docs/man/nng_stream_listener_set.3str.adoc, docs/ref/migrate/nng1.md, docs/ref/tran/ipc.md, docs/ref/xref.md, include/nng/nng.h, src/core/listener.c, src/core/listener.h, src/core/stream.c, src/core/stream.h, src/nng.c, src/platform/posix/posix_ipcwinsec_test.c, src/platform/windows/win_ipc_sec_test.c, src/platform/windows/win_ipclisten.c, src/sp/transport.h, src/sp/transport/ipc/ipc.c, src/sp/transport/ipc/ipc_test.c
=> No more sec desc option

src/core/sockfd.c, src/platform/windows/win_ipclisten.c
=> Stable winipc

src/core/aio.c
=> aio: stop has to wait for expirations to finish

src/sp/transport/udp/udp.c
=> udp: hang on close after sending too large

src/sp/CMakeLists.txt, src/sp/protocol/survey0/respond.c, src/sp/reconnect_stress_test.c
This is same as PRs #1960 and #1965 squashed but for stable branch
=> Backport of issue #1959 fix into stable branch

src/supplemental/http/http_server.c
=> Http aio init

src/sp/transport/inproc/inproc.c
=> Inproc ref

src/sp/transport/tls/tls.c
=> Tls inline 2

src/sp/transport/tls/tls.c, src/sp/transport/ws/websocket.c
=> Websock stop

src/platform/posix/posix_ipc.h, src/platform/posix/posix_ipcconn.c, src/platform/posix/posix_ipcdial.c, src/platform/posix/posix_ipclisten.c, src/platform/posix/posix_pollq.h, src/platform/posix/posix_pollq_epoll.c, src/platform/posix/posix_pollq_epoll.h, src/platform/posix/posix_pollq_kqueue.c, src/platform/posix/posix_pollq_kqueue.h, src/platform/posix/posix_pollq_poll.c, src/platform/posix/posix_pollq_port.c, src/platform/posix/posix_pollq_select.c, src/platform/posix/posix_pollq_select.h, src/platform/posix/posix_sockfd.c, src/platform/posix/posix_tcp.h, src/platform/posix/posix_tcpconn.c, src/platform/posix/posix_tcpdial.c, src/platform/posix/posix_tcplisten.c, src/platform/posix/posix_udp.c
=> Poll alloc

src/platform/posix/posix_ipc.h, src/platform/posix/posix_ipcdial.c, src/sp/transport/ipc/ipc_test.c
=> Ipc dial refcnt

src/platform/posix/posix_pollq_port.c, src/platform/posix/posix_pollq_port.h
=> port events poller (illumos/Solaris): use atomic events mask

src/platform/posix/posix_tcp.h, src/platform/posix/posix_tcpdial.c
=> posix tcp: use common refcnt implementation

src/core/msgqueue.c
=> More defer

src/platform/posix/posix_resolv_gai.c
=> posix resolver: use nni_aio_defer

src/core/taskq.c
This should help some cases of synchronous callers that don't use a callback at all.
=> taskq: skip the lock/unlock if there is no callback

src/core/dialer.c, src/core/tcp.c, src/supplemental/http/http_client.c, src/supplemental/http/http_conn.c
=> Dialer inline aio

src/platform/windows/win_tcpdial.c, src/tools/perf/CMakeLists.txt
=> Win perf tests ci cd

src/platform/posix/posix_pollq_poll.c, src/platform/posix/posix_pollq_port.c
=> Pollq port scale

src/core/socket.c
just a rename of the description.
=> * MDF [core/socket] correct stat desc of rx_bytes

src/sp/transport/ws/ws_test.c, src/supplemental/websocket/wssfile_test.c
=> websocket tests: more resilience against EADDRINUSE

docs/ref/migrate/nng1.md, include/nng/nng.h
=> api: add NNG1_MIGRATION transition assistance macro

demo/async/CMakeLists.txt, demo/async/client.c, demo/async/server.c, demo/http_client/CMakeLists.txt, demo/http_client/http_client.c, demo/pubsub_forwarder/CMakeLists.txt, demo/pubsub_forwarder/pubsub_forwarder.c, demo/raw/CMakeLists.txt, demo/raw/raw.c, demo/reqrep/CMakeLists.txt, demo/reqrep/reqrep.c, demo/rest/CMakeLists.txt, demo/rest/server.c, demo/stream/stream.c, src/CMakeLists.txt, src/supplemental/http/http_msg.c, src/supplemental/tls/mbedtls/CMakeLists.txt, src/supplemental/tls/wolfssl/CMakeLists.txt
=> Cmake tls deps

README.md
=> README: revised information about mdbook

docs/man/nng_options.5.adoc, docs/ref/api/sock.md, docs/ref/xref.md
=> docs: document NNG_OPT_MAXTTL, other cleanups

docs/ref/tran/inproc.md, docs/ref/tran/ipc.md, docs/ref/tran/socket.md, docs/ref/tran/udp.md, docs/ref/xref.md
=> Tran opts docs

docs/man/nng_close.3.adoc, docs/man/nng_recv.3.adoc, docs/man/nng_send.3.adoc, include/nng/nng.h, src/core/aio_test.c, src/nng.c
=> Stable socket close

include/nng/http.h, src/supplemental/http/http_api.h, src/supplemental/http/http_client.c, src/supplemental/http/http_conn.c, src/supplemental/http/http_msg.c, src/supplemental/http/http_msg.h, src/supplemental/http/http_public.c, src/supplemental/http/http_server.c
=> Http no res req

docs/ref/api/http.md, include/nng/http.h, src/supplemental/http/http_api.h, src/supplemental/http/http_client.c, src/supplemental/http/http_conn.c, src/supplemental/http/http_msg.c, src/supplemental/http/http_msg.h, src/supplemental/http/http_public.c, src/supplemental/http/http_server.c
=> Status fix

src/platform/windows/win_ipclisten.c
=> fixes #2092 nng_close may hang on Windows (stable version)

src/platform/windows/win_ipclisten.c
=> fixes #2092 nng_close may hang on Windows

src/platform/windows/win_io.c
=> Windows: Fix regression where no connections after 5 seconds can occur

src/sp/transport/tls/tls_tran_test.c
=> Fix TLS test.

src/supplemental/http/http_client.c
As being requested here https://github.com/nanomsg/nng/pull/2119
=> * FIX [HTTP] fix a blocking case when freeing http client

include/nng/nng.h, src/core/init.c, src/nng.c
This allow to pass constrant string i particular and constant data in general to nng functions.
If this change is accepted I'd like to extend it to other functions before merged.
=> Make pointers to data that is not modified const.

src/platform/posix/posix_tcplisten.c
=> posix tcp: use after free in listener (need to stop before free)

src/supplemental/tls/tls_common.c, src/supplemental/tls/tls_common.h, src/supplemental/tls/tls_engine.h
=> TLS: eliminate more runtime ops vectors

src/sp/transport/dtls/dtls.c
=> DTLS: hold tls configuration

src/supplemental/http/http_public.c
=> fixes #2150 build error if HTTP support is disabled.
